export const genkiVocab = [{ "kana": "あの", "kanji": "", "meaning": "um...", "lesson": 1 },
{ "kana": "いま", "kanji": "今", "meaning": "now", "lesson": 1 },
{ "kana": "えいご", "kanji": "英語", "meaning": "English (language)", "lesson": 1 },
{ "kana": "がくせい", "kanji": "学生", "meaning": "student", "lesson": 1 },
{ "kana": "〜ご", "kanji": "〜語", "meaning": "language", "lesson": 1 },
{ "kana": "こうこう", "kanji": "高校", "meaning": "high school", "lesson": 1 },
{ "kana": "ごご", "kanji": "午後", "meaning": "P.M.", "lesson": 1 },
{ "kana": "ごぜん", "kanji": "午前", "meaning": "A.M.", "lesson": 1 },
{ "kana": "〜さい", "kanji": "〜歳", "meaning": "...years old", "lesson": 1 },
{ "kana": "〜さん", "kanji": "", "meaning": "Mr./Ms....", "lesson": 1 },
{ "kana": "〜じ", "kanji": "〜時", "meaning": "o'clock", "lesson": 1 },
{ "kana": "〜じん", "kanji": "〜人", "meaning": "people", "lesson": 1 },
{ "kana": "せんせい", "kanji": "先生", "meaning": "teacher; Professor ...", "lesson": 1 },
{ "kana": "せんもん", "kanji": "専門", "meaning": "major", "lesson": 1 },
{ "kana": "そうです", "kanji": "", "meaning": "That's right.", "lesson": 1 },
{ "kana": "だいがく", "kanji": "大学", "meaning": "college; university", "lesson": 1 },
{ "kana": "でんわ", "kanji": "電話", "meaning": "telephone", "lesson": 1 },
{ "kana": "ともだち", "kanji": "友達", "meaning": "friend", "lesson": 1 },
{ "kana": "なまえ", "kanji": "名前", "meaning": "name", "lesson": 1 },
{ "kana": "なん／なに", "kanji": "何", "meaning": "what", "lesson": 1 },
{ "kana": "にほん", "kanji": "日本", "meaning": "Japan", "lesson": 1 },
{ "kana": "〜ねんせい", "kanji": "〜年生", "meaning": "...year student", "lesson": 1 },
{ "kana": "はい", "kanji": "", "meaning": "yes", "lesson": 1 },
{ "kana": "はん", "kanji": "半", "meaning": "half", "lesson": 1 },
{ "kana": "ばんごう", "kanji": "番号", "meaning": "number", "lesson": 1 },
{ "kana": "りゅうがくせい", "kanji": "留学生", "meaning": "international student", "lesson": 1 },
{ "kana": "わたし", "kanji": "私", "meaning": "I", "lesson": 1 },
{ "kana": "アメリカ", "kanji": "", "meaning": "U.S.A.", "lesson": 1 },
{ "kana": "イギリス", "kanji": "", "meaning": "Britain", "lesson": 1 },
{ "kana": "オーストラリア", "kanji": "", "meaning": "Australia", "lesson": 1 },
{ "kana": "かんこく", "kanji": "韓国", "meaning": "Korea", "lesson": 1 },
{ "kana": "スウェーデン", "kanji": "", "meaning": "Sweden", "lesson": 1 },
{ "kana": "ちゅうごく", "kanji": "中国", "meaning": "China", "lesson": 1 },
{ "kana": "かがく", "kanji": "科学", "meaning": "science", "lesson": 1 },
{ "kana": "アジアけんきゅう", "kanji": "アジア研究", "meaning": "Asian studies", "lesson": 1 },
{ "kana": "こくさいかんけい", "kanji": "国際関係", "meaning": "international relations", "lesson": 1 },
{ "kana": "コンピューター", "kanji": "", "meaning": "computer", "lesson": 1 },
{ "kana": "じんるいがく", "kanji": "人類学", "meaning": "anthropology", "lesson": 1 },
{ "kana": "せいじ", "kanji": "政治", "meaning": "politics", "lesson": 1 },
{ "kana": "ビジネス", "kanji": "", "meaning": "business", "lesson": 1 },
{ "kana": "ぶんがく", "kanji": "文学", "meaning": "literature", "lesson": 1 },
{ "kana": "れきし", "kanji": "歴史", "meaning": "history", "lesson": 1 },
{ "kana": "しごと", "kanji": "仕事", "meaning": "job; work; occupation", "lesson": 1 },
{ "kana": "いしゃ", "kanji": "医者", "meaning": "doctor", "lesson": 1 },
{ "kana": "かいしゃいん", "kanji": "会社員", "meaning": "office worker", "lesson": 1 },
{ "kana": "こうこうせい", "kanji": "高校生", "meaning": "high school student", "lesson": 1 },
{ "kana": "しゅふ", "kanji": "主婦", "meaning": "housewife", "lesson": 1 },
{ "kana": "だいがくいんせい", "kanji": "大学院生", "meaning": "graduate student", "lesson": 1 },
{ "kana": "だいがくせい", "kanji": "大学生", "meaning": "college student", "lesson": 1 },
{ "kana": "べんごし", "kanji": "弁護士", "meaning": "lawyer", "lesson": 1 },
{ "kana": "おかあさん", "kanji": "お母さん", "meaning": "mother", "lesson": 1 },
{ "kana": "おとうさん", "kanji": "お父さん", "meaning": "father", "lesson": 1 },
{ "kana": "おねえさん", "kanji": "お姉さん", "meaning": "older sister", "lesson": 1 },
{ "kana": "おにいさん", "kanji": "お兄さん", "meaning": "older brother", "lesson": 1 },
{ "kana": "いもうと", "kanji": "妹", "meaning": "younger sister", "lesson": 1 },
{ "kana": "おとうと", "kanji": "弟", "meaning": "younger brother", "lesson": 1 },
{ "kana": "これ", "kanji": "", "meaning": "this one", "lesson": 2 },
{ "kana": "それ", "kanji": "", "meaning": "that one", "lesson": 2 },
{ "kana": "あれ", "kanji": "", "meaning": "that one (over there)", "lesson": 2 },
{ "kana": "どれ", "kanji": "", "meaning": "which one", "lesson": 2 },
{ "kana": "この", "kanji": "", "meaning": "this ...", "lesson": 2 },
{ "kana": "その", "kanji": "", "meaning": "that ...", "lesson": 2 },
{ "kana": "あの", "kanji": "", "meaning": "that ... (over there)", "lesson": 2 },
{ "kana": "どの", "kanji": "", "meaning": "which ...", "lesson": 2 },
{ "kana": "あそこ", "kanji": "", "meaning": "over there", "lesson": 2 },
{ "kana": "どこ", "kanji": "", "meaning": "where", "lesson": 2 },
{ "kana": "だれ", "kanji": "", "meaning": "who", "lesson": 2 },
{ "kana": "おいしい", "kanji": "", "meaning": "delicious", "lesson": 2 },
{ "kana": "さかな", "kanji": "魚", "meaning": "fish", "lesson": 2 },
{ "kana": "とんかつ", "kanji": "", "meaning": "pork cutlet", "lesson": 2 },
{ "kana": "にく", "kanji": "肉", "meaning": "meat", "lesson": 2 },
{ "kana": "メニュー", "kanji": "", "meaning": "menu", "lesson": 2 },
{ "kana": "やさい", "kanji": "野菜", "meaning": "vegetable", "lesson": 2 },
{ "kana": "えんぴつ", "kanji": "鉛筆", "meaning": "pencil", "lesson": 2 },
{ "kana": "かさ", "kanji": "傘", "meaning": "umbrella", "lesson": 2 },
{ "kana": "かばん", "kanji": "", "meaning": "bag", "lesson": 2 },
{ "kana": "くつ", "kanji": "靴", "meaning": "shoes", "lesson": 2 },
{ "kana": "さいふ", "kanji": "財布", "meaning": "wallet", "lesson": 2 },
{ "kana": "ジーンズ", "kanji": "", "meaning": "jeans", "lesson": 2 },
{ "kana": "じしょ", "kanji": "辞書", "meaning": "dictionary", "lesson": 2 },
{ "kana": "じてんしゃ", "kanji": "自転車", "meaning": "bicycle", "lesson": 2 },
{ "kana": "しんぶん", "kanji": "新聞", "meaning": "newspaper", "lesson": 2 },
{ "kana": "テープ", "kanji": "", "meaning": "tape", "lesson": 2 },
{ "kana": "とけい", "kanji": "時計", "meaning": "watch; clock", "lesson": 2 },
{ "kana": "トレーナー", "kanji": "", "meaning": "sweat shirt", "lesson": 2 },
{ "kana": "ノート", "kanji": "", "meaning": "notebook", "lesson": 2 },
{ "kana": "ペン", "kanji": "", "meaning": "pen", "lesson": 2 },
{ "kana": "ぼうし", "kanji": "帽子", "meaning": "hat; cap", "lesson": 2 },
{ "kana": "ほん", "kanji": "本", "meaning": "book", "lesson": 2 },
{ "kana": "おてあらい", "kanji": "お手洗い", "meaning": "restroom", "lesson": 2 },
{ "kana": "きっさてん", "kanji": "喫茶店", "meaning": "cafe", "lesson": 2 },
{ "kana": "ぎんこう", "kanji": "銀行", "meaning": "bank", "lesson": 2 },
{ "kana": "としょかん", "kanji": "図書館", "meaning": "library", "lesson": 2 },
{ "kana": "ゆうびんきょく", "kanji": "郵便局", "meaning": "post office", "lesson": 2 },
{ "kana": "けいざい", "kanji": "経済", "meaning": "economics", "lesson": 2 },
{ "kana": "いくら", "kanji": "", "meaning": "how much", "lesson": 2 },
{ "kana": "〜えん", "kanji": "〜円", "meaning": "...yen", "lesson": 2 },
{ "kana": "たかい", "kanji": "高い", "meaning": "expensive", "lesson": 2 },
{ "kana": "いらっしゃいませ", "kanji": "", "meaning": "Welcome (to our store)", "lesson": 2 },
{ "kana": "（〜を）おねがいします", "kanji": "", "meaning": "..., please.", "lesson": 2 },
{ "kana": "（〜を）ください", "kanji": "", "meaning": "Please give me...", "lesson": 2 },
{ "kana": "じゃあ", "kanji": "", "meaning": "then...; if that is the case,...", "lesson": 2 },
{ "kana": "（〜を）どうぞ", "kanji": "", "meaning": "Here it is.", "lesson": 2 },
{ "kana": "どうも", "kanji": "", "meaning": "Thank you.", "lesson": 2 },
{ "kana": "えいが", "kanji": "映画", "meaning": "movie", "lesson": 3 },
{ "kana": "おんがく", "kanji": "音楽", "meaning": "music", "lesson": 3 },
{ "kana": "ざっし", "kanji": "雑誌", "meaning": "magazine", "lesson": 3 },
{ "kana": "スポーツ", "kanji": "", "meaning": "sports", "lesson": 3 },
{ "kana": "デート", "kanji": "", "meaning": "date (romantic, not calendar)", "lesson": 3 },
{ "kana": "テニス", "kanji": "", "meaning": "tennis", "lesson": 3 },
{ "kana": "テレビ", "kanji": "", "meaning": "TV", "lesson": 3 },
{ "kana": "ビデオ", "kanji": "", "meaning": "video tape; VCR", "lesson": 3 },
{ "kana": "あさごはん", "kanji": "朝御飯", "meaning": "breakfast", "lesson": 3 },
{ "kana": "おさけ", "kanji": "お酒", "meaning": "sake; alcohol", "lesson": 3 },
{ "kana": "おちゃ", "kanji": "お茶", "meaning": "green tea", "lesson": 3 },
{ "kana": "コーヒー", "kanji": "", "meaning": "coffee", "lesson": 3 },
{ "kana": "ばんごはん", "kanji": "晩御飯", "meaning": "dinner", "lesson": 3 },
{ "kana": "ハンバーガー", "kanji": "", "meaning": "hamburger", "lesson": 3 },
{ "kana": "ひるごはん", "kanji": "昼御飯", "meaning": "lunch", "lesson": 3 },
{ "kana": "みず", "kanji": "水", "meaning": "water", "lesson": 3 },
{ "kana": "いえ", "kanji": "家", "meaning": "home; house", "lesson": 3 },
{ "kana": "うち", "kanji": "家", "meaning": "home; house; my place", "lesson": 3 },
{ "kana": "LL（エルエル）", "kanji": "", "meaning": "language lab", "lesson": 3 },
{ "kana": "がっこう", "kanji": "学校", "meaning": "school", "lesson": 3 },
{ "kana": "あさ", "kanji": "朝", "meaning": "morning", "lesson": 3 },
{ "kana": "あした", "kanji": "", "meaning": "tomorrow", "lesson": 3 },
{ "kana": "いつ", "kanji": "", "meaning": "when", "lesson": 3 },
{ "kana": "きょう", "kanji": "今日", "meaning": "today", "lesson": 3 },
{ "kana": "〜ごろ", "kanji": "", "meaning": "at about", "lesson": 3 },
{ "kana": "こんばん", "kanji": "今晩", "meaning": "tonight", "lesson": 3 },
{ "kana": "しゅうまつ", "kanji": "週末", "meaning": "weekend", "lesson": 3 },
{ "kana": "どようび", "kanji": "土曜日", "meaning": "Saturday", "lesson": 3 },
{ "kana": "にちようび", "kanji": "日曜日", "meaning": "Sunday", "lesson": 3 },
{ "kana": "まいにち", "kanji": "毎日", "meaning": "every day", "lesson": 3 },
{ "kana": "まいばん", "kanji": "毎晩", "meaning": "every night", "lesson": 3 },
{ "kana": "いく", "kanji": "行く", "meaning": "to go", "lesson": 3 },
{ "kana": "かえる", "kanji": "帰る", "meaning": "to go back; to return", "lesson": 3 },
{ "kana": "きく", "kanji": "聞く", "meaning": "to listen; to hear", "lesson": 3 },
{ "kana": "のむ", "kanji": "飲む", "meaning": "to drink", "lesson": 3 },
{ "kana": "はなす", "kanji": "話す", "meaning": "to speak; to talk", "lesson": 3 },
{ "kana": "よむ", "kanji": "読む", "meaning": "to read", "lesson": 3 },
{ "kana": "おきる", "kanji": "起きる", "meaning": "to get up", "lesson": 3 },
{ "kana": "たべる", "kanji": "食べる", "meaning": "to eat", "lesson": 3 },
{ "kana": "ねる", "kanji": "寝る", "meaning": "to sleep; to go to sleep", "lesson": 3 },
{ "kana": "みる", "kanji": "見る", "meaning": "to see; to look at; to watch", "lesson": 3 },
{ "kana": "くる", "kanji": "来る", "meaning": "to come", "lesson": 3 },
{ "kana": "する", "kanji": "", "meaning": "to do", "lesson": 3 },
{ "kana": "べんきょうする", "kanji": "勉強する", "meaning": "to study", "lesson": 3 },
{ "kana": "いい", "kanji": "", "meaning": "good", "lesson": 3 },
{ "kana": "はやい", "kanji": "早い", "meaning": "early", "lesson": 3 },
{ "kana": "あまり+ negative", "kanji": "", "meaning": "not much", "lesson": 3 },
{ "kana": "ぜんぜん + negative", "kanji": "全然", "meaning": "not at all", "lesson": 3 },
{ "kana": "たいてい", "kanji": "大抵", "meaning": "usually", "lesson": 3 },
{ "kana": "ちょっと", "kanji": "", "meaning": "a little", "lesson": 3 },
{ "kana": "ときどき", "kanji": "時々", "meaning": "sometimes", "lesson": 3 },
{ "kana": "よく", "kanji": "", "meaning": "often; much", "lesson": 3 },
{ "kana": "そうですね", "kanji": "", "meaning": "That's right.; Let me see.", "lesson": 3 },
{ "kana": "でも", "kanji": "", "meaning": "but", "lesson": 3 },
{ "kana": "どうですか", "kanji": "", "meaning": "How about...?; How is...?", "lesson": 3 },
{ "kana": "アルバイト", "kanji": "", "meaning": "part-time job", "lesson": 4 },
{ "kana": "かいもの", "kanji": "買い物", "meaning": "shopping", "lesson": 4 },
{ "kana": "クラス", "kanji": "", "meaning": "class", "lesson": 4 },
{ "kana": "あなた", "kanji": "", "meaning": "you", "lesson": 4 },
{ "kana": "いぬ", "kanji": "犬", "meaning": "dog", "lesson": 4 },
{ "kana": "おみやげ", "kanji": "お土産", "meaning": "souvenir", "lesson": 4 },
{ "kana": "こども", "kanji": "子供", "meaning": "child", "lesson": 4 },
{ "kana": "ごはん", "kanji": "御飯", "meaning": "rice; meal", "lesson": 4 },
{ "kana": "しゃしん", "kanji": "写真", "meaning": "picture; photograph", "lesson": 4 },
{ "kana": "つくえ", "kanji": "机", "meaning": "desk", "lesson": 4 },
{ "kana": "てがみ", "kanji": "手紙", "meaning": "letter", "lesson": 4 },
{ "kana": "ねこ", "kanji": "猫", "meaning": "cat", "lesson": 4 },
{ "kana": "パン", "kanji": "", "meaning": "bread", "lesson": 4 },
{ "kana": "ひと", "kanji": "人", "meaning": "person", "lesson": 4 },
{ "kana": "おてら", "kanji": "お寺", "meaning": "temple", "lesson": 4 },
{ "kana": "こうえん", "kanji": "公園", "meaning": "park", "lesson": 4 },
{ "kana": "スーパー", "kanji": "", "meaning": "supermarket", "lesson": 4 },
{ "kana": "デパート", "kanji": "", "meaning": "department store", "lesson": 4 },
{ "kana": "バスてい", "kanji": "バス停", "meaning": "bus stop", "lesson": 4 },
{ "kana": "びょういん", "kanji": "病院", "meaning": "hospital", "lesson": 4 },
{ "kana": "ホテル", "kanji": "", "meaning": "hotel", "lesson": 4 },
{ "kana": "ほんや", "kanji": "本屋", "meaning": "bookstore", "lesson": 4 },
{ "kana": "まち", "kanji": "町", "meaning": "town; city", "lesson": 4 },
{ "kana": "レストラン", "kanji": "", "meaning": "restaurant", "lesson": 4 },
{ "kana": "きのう", "kanji": "昨日", "meaning": "yesterday", "lesson": 4 },
{ "kana": "さっき", "kanji": "", "meaning": "a little while ago", "lesson": 4 },
{ "kana": "〜じかん", "kanji": "〜時間", "meaning": "hour", "lesson": 4 },
{ "kana": "いちじかん", "kanji": "一時間", "meaning": "one hour", "lesson": 4 },
{ "kana": "せんしゅう", "kanji": "先週", "meaning": "last week", "lesson": 4 },
{ "kana": "とき", "kanji": "時", "meaning": "when...; at the time of...", "lesson": 4 },
{ "kana": "かようび", "kanji": "火曜日", "meaning": "Tuesday", "lesson": 4 },
{ "kana": "すいようび", "kanji": "水曜日", "meaning": "Wednesday", "lesson": 4 },
{ "kana": "もくようび", "kanji": "木曜日", "meaning": "Thursday", "lesson": 4 },
{ "kana": "きんようび", "kanji": "金曜日", "meaning": "Friday", "lesson": 4 },
{ "kana": "あう", "kanji": "会う", "meaning": "to meet; to see (a person)", "lesson": 4 },
{ "kana": "ある", "kanji": "", "meaning": "there is ...", "lesson": 4 },
{ "kana": "かう", "kanji": "買う", "meaning": "to buy", "lesson": 4 },
{ "kana": "かく", "kanji": "書く", "meaning": "to write", "lesson": 4 },
{ "kana": "とる", "kanji": "撮る", "meaning": "to take (pictures)", "lesson": 4 },
{ "kana": "まつ", "kanji": "待つ", "meaning": "to wait", "lesson": 4 },
{ "kana": "わかる", "kanji": "", "meaning": "to understand", "lesson": 4 },
{ "kana": "いる", "kanji": "", "meaning": "(a person) is in ...; stays at ...", "lesson": 4 },
{ "kana": "〜ぐらい", "kanji": "", "meaning": "about (approximate measurement)", "lesson": 4 },
{ "kana": "ごめんなさい", "kanji": "", "meaning": "I'm sorry.", "lesson": 4 },
{ "kana": "だから", "kanji": "", "meaning": "so; therefore", "lesson": 4 },
{ "kana": "たくさん", "kanji": "", "meaning": "many; a lot", "lesson": 4 },
{ "kana": "〜と", "kanji": "", "meaning": "together with (a person)", "lesson": 4 },
{ "kana": "どうして", "kanji": "", "meaning": "why", "lesson": 4 },
{ "kana": "ひとりで", "kanji": "一人で", "meaning": "alone", "lesson": 4 },
{ "kana": "もしもし", "kanji": "", "meaning": "Hello? (used on the phone)", "lesson": 4 },
{ "kana": "みぎ", "kanji": "右", "meaning": "right", "lesson": 4 },
{ "kana": "ひだり", "kanji": "左", "meaning": "left", "lesson": 4 },
{ "kana": "まえ", "kanji": "前", "meaning": "front", "lesson": 4 },
{ "kana": "うしろ", "kanji": "後ろ", "meaning": "back", "lesson": 4 },
{ "kana": "なか", "kanji": "中", "meaning": "inside", "lesson": 4 },
{ "kana": "うえ", "kanji": "上", "meaning": "on", "lesson": 4 },
{ "kana": "した", "kanji": "下", "meaning": "under", "lesson": 4 },
{ "kana": "そば", "kanji": "", "meaning": "near", "lesson": 4 },
{ "kana": "となり", "kanji": "隣", "meaning": "next", "lesson": 4 },
{ "kana": "あいだ", "kanji": "間", "meaning": "between", "lesson": 4 },
{ "kana": "そこ", "kanji": "", "meaning": "there", "lesson": 4 },
{ "kana": "ここ", "kanji": "", "meaning": "here", "lesson": 4 },
{ "kana": "げつようび", "kanji": "月曜日", "meaning": "Monday", "lesson": 4 },
{ "kana": "うみ", "kanji": "海", "meaning": "sea", "lesson": 5 },
{ "kana": "きって", "kanji": "切手", "meaning": "postal stamps", "lesson": 5 },
{ "kana": "きっぷ", "kanji": "切符", "meaning": "ticket", "lesson": 5 },
{ "kana": "サーフィン", "kanji": "", "meaning": "surfing", "lesson": 5 },
{ "kana": "しゅくだい", "kanji": "宿題", "meaning": "homework", "lesson": 5 },
{ "kana": "たべもの", "kanji": "食べ物", "meaning": "food", "lesson": 5 },
{ "kana": "たんじょうび", "kanji": "誕生日", "meaning": "birthday", "lesson": 5 },
{ "kana": "テスト", "kanji": "", "meaning": "test", "lesson": 5 },
{ "kana": "てんき", "kanji": "天気", "meaning": "weather", "lesson": 5 },
{ "kana": "のみもの", "kanji": "飲み物", "meaning": "drink", "lesson": 5 },
{ "kana": "はがき", "kanji": "葉書", "meaning": "postcard", "lesson": 5 },
{ "kana": "バス", "kanji": "", "meaning": "bus", "lesson": 5 },
{ "kana": "ひこうき", "kanji": "飛行機", "meaning": "airplane", "lesson": 5 },
{ "kana": "へや", "kanji": "部屋", "meaning": "room", "lesson": 5 },
{ "kana": "ぼく", "kanji": "僕", "meaning": "I (used by men)", "lesson": 5 },
{ "kana": "やすみ", "kanji": "休み", "meaning": "holiday; day off; absence", "lesson": 5 },
{ "kana": "りょこう", "kanji": "旅行", "meaning": "travel", "lesson": 5 },
{ "kana": "あたらしい", "kanji": "新しい", "meaning": "new", "lesson": 5 },
{ "kana": "あつい", "kanji": "暑い", "meaning": "hot (weather)", "lesson": 5 },
{ "kana": "あつい", "kanji": "熱い", "meaning": "hot (objects)", "lesson": 5 },
{ "kana": "いそがしい", "kanji": "忙しい", "meaning": "busy (people/days)", "lesson": 5 },
{ "kana": "おおきい", "kanji": "大きい", "meaning": "large", "lesson": 5 },
{ "kana": "おもしろい", "kanji": "面白い", "meaning": "interesting", "lesson": 5 },
{ "kana": "こわい", "kanji": "怖い", "meaning": "frightening", "lesson": 5 },
{ "kana": "さむい", "kanji": "寒い", "meaning": "cold (weather-not used for objects)", "lesson": 5 },
{ "kana": "たのしい", "kanji": "楽しい", "meaning": "fun", "lesson": 5 },
{ "kana": "ちいさい", "kanji": "小さい", "meaning": "small", "lesson": 5 },
{ "kana": "つまらない", "kanji": "", "meaning": "boring", "lesson": 5 },
{ "kana": "ふるい", "kanji": "古い", "meaning": "old (thing - not used for people)", "lesson": 5 },
{ "kana": "むずかしい", "kanji": "難しい", "meaning": "difficult", "lesson": 5 },
{ "kana": "やさしい", "kanji": "", "meaning": "easy (problem); kind (person)", "lesson": 5 },
{ "kana": "やすい", "kanji": "安い", "meaning": "inexpensive; cheap (thing)", "lesson": 5 },
{ "kana": "きらい（な）", "kanji": "嫌い", "meaning": "disgusted with; to dislike", "lesson": 5 },
{ "kana": "きれい（な）", "kanji": "", "meaning": "beautiful; clean", "lesson": 5 },
{ "kana": "げんき（な）", "kanji": "元気", "meaning": "healthy; energetic", "lesson": 5 },
{ "kana": "しずか（な）", "kanji": "静か", "meaning": "quiet", "lesson": 5 },
{ "kana": "すき（な）", "kanji": "好き", "meaning": "fond of; to like", "lesson": 5 },
{ "kana": "だいきらい（な）", "kanji": "大嫌い", "meaning": "to hate", "lesson": 5 },
{ "kana": "だいすき（な）", "kanji": "大好き", "meaning": "very fond of; to love", "lesson": 5 },
{ "kana": "にぎやか（な）", "kanji": "", "meaning": "lively", "lesson": 5 },
{ "kana": "ハンサム（な）", "kanji": "", "meaning": "handsome", "lesson": 5 },
{ "kana": "ひま（な）", "kanji": "暇", "meaning": "not busy; to have a lot of free time", "lesson": 5 },
{ "kana": "およぐ", "kanji": "泳ぐ", "meaning": "to swim", "lesson": 5 },
{ "kana": "きく", "kanji": "聞く", "meaning": "to ask", "lesson": 5 },
{ "kana": "のる", "kanji": "乗る", "meaning": "to ride; to board", "lesson": 5 },
{ "kana": "やる", "kanji": "", "meaning": "to do; to perform", "lesson": 5 },
{ "kana": "でかける", "kanji": "出かける", "meaning": "to go out", "lesson": 5 },
{ "kana": "いっしょに", "kanji": "一緒に", "meaning": "together", "lesson": 5 },
{ "kana": "それから", "kanji": "", "meaning": "and then", "lesson": 5 },
{ "kana": "だいじょうぶ", "kanji": "大丈夫", "meaning": "It's okay.; Not to worry.; Everything is under control.", "lesson": 5 },
{ "kana": "とても", "kanji": "", "meaning": "very", "lesson": 5 },
{ "kana": "どんな", "kanji": "", "meaning": "what kind of...", "lesson": 5 },
{ "kana": "〜まい", "kanji": "〜枚", "meaning": "[counter for flat objects]", "lesson": 5 },
{ "kana": "〜まで", "kanji": "", "meaning": "to (a place); as far as (a place); till (a time)", "lesson": 5 },
{ "kana": "おかね", "kanji": "お金", "meaning": "money", "lesson": 6 },
{ "kana": "おばあさん", "kanji": "", "meaning": "grandmother; old woman", "lesson": 6 },
{ "kana": "おふろ", "kanji": "お風呂", "meaning": "bath", "lesson": 6 },
{ "kana": "かんじ", "kanji": "漢字", "meaning": "kanji; Chinese character", "lesson": 6 },
{ "kana": "きょうかしょ", "kanji": "教科書", "meaning": "textbook", "lesson": 6 },
{ "kana": "こんしゅう", "kanji": "今週", "meaning": "this week", "lesson": 6 },
{ "kana": "しみんびょういん", "kanji": "市民病院", "meaning": "Municipal Hospital", "lesson": 6 },
{ "kana": "つぎ", "kanji": "次", "meaning": "next", "lesson": 6 },
{ "kana": "テレビゲーム", "kanji": "", "meaning": "video game", "lesson": 6 },
{ "kana": "でんき", "kanji": "電気", "meaning": "electricity", "lesson": 6 },
{ "kana": "でんしゃ", "kanji": "電車", "meaning": "train", "lesson": 6 },
{ "kana": "にもつ", "kanji": "荷物", "meaning": "baggage", "lesson": 6 },
{ "kana": "ページ", "kanji": "", "meaning": "page", "lesson": 6 },
{ "kana": "まど", "kanji": "窓", "meaning": "window", "lesson": 6 },
{ "kana": "よる", "kanji": "夜", "meaning": "night", "lesson": 6 },
{ "kana": "らいしゅう", "kanji": "来週", "meaning": "next week", "lesson": 6 },
{ "kana": "らいねん", "kanji": "来年", "meaning": "next year", "lesson": 6 },
{ "kana": "たいへん（な）", "kanji": "大変", "meaning": "tough (situation)", "lesson": 6 },
{ "kana": "あそぶ", "kanji": "遊ぶ", "meaning": "to play; to spend time pleasantly", "lesson": 6 },
{ "kana": "いそぐ", "kanji": "急ぐ", "meaning": "to hurry", "lesson": 6 },
{ "kana": "おふろにはいる", "kanji": "お風呂に入る", "meaning": "to take a bath", "lesson": 6 },
{ "kana": "かえす", "kanji": "返す", "meaning": "to return (things)", "lesson": 6 },
{ "kana": "けす", "kanji": "消す", "meaning": "to turn off; to erase", "lesson": 6 },
{ "kana": "しぬ", "kanji": "死ぬ", "meaning": "to die", "lesson": 6 },
{ "kana": "すわる", "kanji": "座る", "meaning": "to sit down", "lesson": 6 },
{ "kana": "たつ", "kanji": "立つ", "meaning": "to stand up", "lesson": 6 },
{ "kana": "たばこをすう", "kanji": "たばこを吸う", "meaning": "to smoke", "lesson": 6 },
{ "kana": "つかう", "kanji": "使う", "meaning": "to use", "lesson": 6 },
{ "kana": "てつだう", "kanji": "手伝う", "meaning": "to help", "lesson": 6 },
{ "kana": "はいる", "kanji": "入る", "meaning": "to enter", "lesson": 6 },
{ "kana": "もつ", "kanji": "持つ", "meaning": "to carry; to hold", "lesson": 6 },
{ "kana": "やすむ", "kanji": "休む", "meaning": "to be absent (from...); to rest", "lesson": 6 },
{ "kana": "あける", "kanji": "開ける", "meaning": "to open (something)", "lesson": 6 },
{ "kana": "おしえる", "kanji": "教える", "meaning": "to teach; to instruct", "lesson": 6 },
{ "kana": "おりる", "kanji": "降りる", "meaning": "to get off", "lesson": 6 },
{ "kana": "かりる", "kanji": "借りる", "meaning": "to borrow", "lesson": 6 },
{ "kana": "しめる", "kanji": "閉める", "meaning": "to close (something)", "lesson": 6 },
{ "kana": "つける", "kanji": "", "meaning": "to turn on", "lesson": 6 },
{ "kana": "でんわをかける", "kanji": "電話をかける", "meaning": "to make a phone call", "lesson": 6 },
{ "kana": "わすれる", "kanji": "忘れる", "meaning": "to forget; to leave behind", "lesson": 6 },
{ "kana": "つれてくる", "kanji": "連れてくる", "meaning": "to bring (a person)", "lesson": 6 },
{ "kana": "もってくる", "kanji": "持ってくる", "meaning": "to bring (a thing)", "lesson": 6 },
{ "kana": "あとで", "kanji": "後で", "meaning": "later on", "lesson": 6 },
{ "kana": "おそく", "kanji": "遅く", "meaning": "(do something) late", "lesson": 6 },
{ "kana": "〜から", "kanji": "", "meaning": "because ...", "lesson": 6 },
{ "kana": "けっこうです", "kanji": "結構です", "meaning": "That would be fine.; That wouldn't be necessary.", "lesson": 6 },
{ "kana": "すぐ", "kanji": "", "meaning": "right away", "lesson": 6 },
{ "kana": "ほんとうですか", "kanji": "本当ですか", "meaning": "Really?", "lesson": 6 },
{ "kana": "ゆっくり", "kanji": "", "meaning": "slowly; leisurely; unhurriedly", "lesson": 6 },
{ "kana": "あね", "kanji": "姉", "meaning": "(my) older sister", "lesson": 7 },
{ "kana": "アパート", "kanji": "", "meaning": "apartment", "lesson": 7 },
{ "kana": "いもうと", "kanji": "妹", "meaning": "younger sister", "lesson": 7 },
{ "kana": "うた", "kanji": "歌", "meaning": "song", "lesson": 7 },
{ "kana": "おとうと", "kanji": "弟", "meaning": "younger brother", "lesson": 7 },
{ "kana": "おとこのひと", "kanji": "男の人", "meaning": "man", "lesson": 7 },
{ "kana": "おにいさん", "kanji": "お兄さん", "meaning": "older brother", "lesson": 7 },
{ "kana": "おねえさん", "kanji": "お姉さん", "meaning": "older sister", "lesson": 7 },
{ "kana": "おんなのひと", "kanji": "女の人", "meaning": "woman", "lesson": 7 },
{ "kana": "かいしゃ", "kanji": "会社", "meaning": "company", "lesson": 7 },
{ "kana": "かぞく", "kanji": "家族", "meaning": "family", "lesson": 7 },
{ "kana": "かみ", "kanji": "髪", "meaning": "hair", "lesson": 7 },
{ "kana": "きょうだい", "kanji": "兄弟", "meaning": "brothers and sisters", "lesson": 7 },
{ "kana": "くに", "kanji": "国", "meaning": "country; place of origin", "lesson": 7 },
{ "kana": "くるま", "kanji": "車", "meaning": "car", "lesson": 7 },
{ "kana": "コンビニ", "kanji": "", "meaning": "convenience store", "lesson": 7 },
{ "kana": "しょくどう", "kanji": "食堂", "meaning": "cafeteria; dining commons", "lesson": 7 },
{ "kana": "ちち", "kanji": "父", "meaning": "(my) father", "lesson": 7 },
{ "kana": "Tシャツ", "kanji": "", "meaning": "T-shirt", "lesson": 7 },
{ "kana": "め", "kanji": "目", "meaning": "eye", "lesson": 7 },
{ "kana": "めがね", "kanji": "眼鏡", "meaning": "glasses", "lesson": 7 },
{ "kana": "あたまがいい", "kanji": "頭がいい", "meaning": "bright; smart; clever", "lesson": 7 },
{ "kana": "かっこいい", "kanji": "", "meaning": "great-looking", "lesson": 7 },
{ "kana": "かわいい", "kanji": "", "meaning": "cute", "lesson": 7 },
{ "kana": "せがたかい", "kanji": "背が高い", "meaning": "tall", "lesson": 7 },
{ "kana": "せがひくい", "kanji": "背が低い", "meaning": "short (stature)", "lesson": 7 },
{ "kana": "ながい", "kanji": "長い", "meaning": "long", "lesson": 7 },
{ "kana": "はやい", "kanji": "早い", "meaning": "fast", "lesson": 7 },
{ "kana": "みじかい", "kanji": "短い", "meaning": "short (length)", "lesson": 7 },
{ "kana": "しんせつ", "kanji": "親切", "meaning": "kind", "lesson": 7 },
{ "kana": "べんり", "kanji": "便利", "meaning": "convenient", "lesson": 7 },
{ "kana": "うたう", "kanji": "歌う", "meaning": "to sing", "lesson": 7 },
{ "kana": "かぶる", "kanji": "", "meaning": "to put on (a hat)", "lesson": 7 },
{ "kana": "しる", "kanji": "知る", "meaning": "to get to know", "lesson": 7 },
{ "kana": "しっています", "kanji": "知っています", "meaning": "I know", "lesson": 7 },
{ "kana": "しりません", "kanji": "知りません", "meaning": "I do not know", "lesson": 7 },
{ "kana": "すむ", "kanji": "住む", "meaning": "to live", "lesson": 7 },
{ "kana": "はく", "kanji": "", "meaning": "to put on (items below your waist)", "lesson": 7 },
{ "kana": "ふとる", "kanji": "太る", "meaning": "to gain weight", "lesson": 7 },
{ "kana": "ふとっています", "kanji": "太っています", "meaning": "to be on the heavy side", "lesson": 7 },
{ "kana": "めがねをかける", "kanji": "", "meaning": "to put on glasses", "lesson": 7 },
{ "kana": "きる", "kanji": "着る", "meaning": "to put on (clothes above your waist)", "lesson": 7 },
{ "kana": "やせる", "kanji": "", "meaning": "to lose weight", "lesson": 7 },
{ "kana": "やせています", "kanji": "", "meaning": "to be thin", "lesson": 7 },
{ "kana": "けっこんする", "kanji": "結婚する", "meaning": "to get married", "lesson": 7 },
{ "kana": "が", "kanji": "", "meaning": "but", "lesson": 7 },
{ "kana": "ひとり", "kanji": "一人", "meaning": "one person", "lesson": 7 },
{ "kana": "ふたり", "kanji": "二人", "meaning": "two people", "lesson": 7 },
{ "kana": "もちろん", "kanji": "", "meaning": "of course", "lesson": 7 },
{ "kana": "よかったら", "kanji": "", "meaning": "if you like", "lesson": 7 },
{ "kana": "ざんねんですね", "kanji": "残念ですね", "meaning": "That's too bad.", "lesson": 8 },
{ "kana": "あさって", "kanji": "", "meaning": "the day after tomorrow", "lesson": 8 },
{ "kana": "あめ", "kanji": "雨", "meaning": "rain", "lesson": 8 },
{ "kana": "かいしゃいん", "kanji": "会社員", "meaning": "office worker", "lesson": 8 },
{ "kana": "カメラ", "kanji": "", "meaning": "camera", "lesson": 8 },
{ "kana": "カラオケ", "kanji": "", "meaning": "karaoke", "lesson": 8 },
{ "kana": "くうき", "kanji": "空気", "meaning": "air", "lesson": 8 },
{ "kana": "けさ", "kanji": "今朝", "meaning": "this morning", "lesson": 8 },
{ "kana": "こんげつ", "kanji": "今月", "meaning": "this month", "lesson": 8 },
{ "kana": "しごと", "kanji": "仕事", "meaning": "job; work; occupation", "lesson": 8 },
{ "kana": "だいがくせい", "kanji": "大学生", "meaning": "college student", "lesson": 8 },
{ "kana": "ディスコ", "kanji": "", "meaning": "disco", "lesson": 8 },
{ "kana": "てんきよほう", "kanji": "天気予報", "meaning": "weather forecast", "lesson": 8 },
{ "kana": "ところ", "kanji": "所", "meaning": "place", "lesson": 8 },
{ "kana": "トマト", "kanji": "", "meaning": "tomato", "lesson": 8 },
{ "kana": "なつ", "kanji": "夏", "meaning": "summer", "lesson": 8 },
{ "kana": "なにか", "kanji": "何か", "meaning": "something", "lesson": 8 },
{ "kana": "パーティー", "kanji": "", "meaning": "party", "lesson": 8 },
{ "kana": "バーベキュー", "kanji": "", "meaning": "barbecue", "lesson": 8 },
{ "kana": "はし", "kanji": "", "meaning": "chopsticks", "lesson": 8 },
{ "kana": "ふゆ", "kanji": "冬", "meaning": "winter", "lesson": 8 },
{ "kana": "ホームステイ", "kanji": "", "meaning": "homestay; living with a local family", "lesson": 8 },
{ "kana": "まいしゅう", "kanji": "毎週", "meaning": "every week", "lesson": 8 },
{ "kana": "らいげつ", "kanji": "来月", "meaning": "next month", "lesson": 8 },
{ "kana": "じょうず", "kanji": "上手", "meaning": "skillful; good at...", "lesson": 8 },
{ "kana": "へた", "kanji": "下手", "meaning": "clumsy; poor at...", "lesson": 8 },
{ "kana": "ゆうめい", "kanji": "有名", "meaning": "famous", "lesson": 8 },
{ "kana": "あめがふる", "kanji": "雨が降る", "meaning": "it rains", "lesson": 8 },
{ "kana": "あらう", "kanji": "洗う", "meaning": "to wash", "lesson": 8 },
{ "kana": "いう", "kanji": "言う", "meaning": "to say", "lesson": 8 },
{ "kana": "いる", "kanji": "", "meaning": "to need", "lesson": 8 },
{ "kana": "おそくなる", "kanji": "遅くなる", "meaning": "to be late (for ...)", "lesson": 8 },
{ "kana": "おもう", "kanji": "思う", "meaning": "to think", "lesson": 8 },
{ "kana": "きる", "kanji": "切る", "meaning": "to cut", "lesson": 8 },
{ "kana": "つくる", "kanji": "作る", "meaning": "to make", "lesson": 8 },
{ "kana": "もっていく", "kanji": "持っていく", "meaning": "to take (something)", "lesson": 8 },
{ "kana": "じろじろみる", "kanji": "じろじろ見る", "meaning": "to stare (at ...)", "lesson": 8 },
{ "kana": "はじめる", "kanji": "始める", "meaning": "to begin", "lesson": 8 },
{ "kana": "うんてんする", "kanji": "運転する", "meaning": "to drive", "lesson": 8 },
{ "kana": "せんたくする", "kanji": "洗濯する", "meaning": "to do laundry", "lesson": 8 },
{ "kana": "そうじする", "kanji": "掃除する", "meaning": "to clean", "lesson": 8 },
{ "kana": "りょうりする", "kanji": "料理する", "meaning": "to cook", "lesson": 8 },
{ "kana": "ううん", "kanji": "", "meaning": "uh-uh; no", "lesson": 8 },
{ "kana": "うん", "kanji": "", "meaning": "uh-huh; yes", "lesson": 8 },
{ "kana": "かんぱい", "kanji": "乾杯", "meaning": "Cheers! (a toast)", "lesson": 8 },
{ "kana": "みんなで", "kanji": "", "meaning": "all (of the people) together", "lesson": 8 },
{ "kana": "いいこ", "kanji": "いい子", "meaning": "good child", "lesson": 9 },
{ "kana": "いろ", "kanji": "色", "meaning": "color", "lesson": 9 },
{ "kana": "おべんとう", "kanji": "お弁当", "meaning": "boxed lunch", "lesson": 9 },
{ "kana": "おんせん", "kanji": "温泉", "meaning": "spa; hot spring", "lesson": 9 },
{ "kana": "かぶき", "kanji": "", "meaning": "Kabuki; traditional Japanese theatrical art", "lesson": 9 },
{ "kana": "ギター", "kanji": "", "meaning": "guitar", "lesson": 9 },
{ "kana": "くすり", "kanji": "薬", "meaning": "medicine", "lesson": 9 },
{ "kana": "くすりをのむ", "kanji": "薬を飲む", "meaning": "to take medicine", "lesson": 9 },
{ "kana": "コンサート", "kanji": "", "meaning": "concert", "lesson": 9 },
{ "kana": "こんど", "kanji": "今度", "meaning": "near future", "lesson": 9 },
{ "kana": "さくぶん", "kanji": "作文", "meaning": "essay; composition", "lesson": 9 },
{ "kana": "しけん", "kanji": "試験", "meaning": "exam", "lesson": 9 },
{ "kana": "しんかんせん", "kanji": "新幹線", "meaning": "Shinkansen; ", "lesson": 9 },
{ "kana": "スキー", "kanji": "", "meaning": "ski", "lesson": 9 },
{ "kana": "せんげつ", "kanji": "先月", "meaning": "last month", "lesson": 9 },
{ "kana": "たんご", "kanji": "単語", "meaning": "word; vocabulary", "lesson": 9 },
{ "kana": "ピアノ", "kanji": "", "meaning": "piano", "lesson": 9 },
{ "kana": "びょうき", "kanji": "病気", "meaning": "illness; sickness", "lesson": 9 },
{ "kana": "あおい", "kanji": "青い", "meaning": "blue", "lesson": 9 },
{ "kana": "あかい", "kanji": "赤い", "meaning": "red", "lesson": 9 },
{ "kana": "くろい", "kanji": "黒い", "meaning": "black", "lesson": 9 },
{ "kana": "さびしい", "kanji": "寂しい", "meaning": "lonely", "lesson": 9 },
{ "kana": "しろい", "kanji": "白い", "meaning": "white", "lesson": 9 },
{ "kana": "わかい", "kanji": "若い", "meaning": "young", "lesson": 9 },
{ "kana": "いじわる", "kanji": "意地悪", "meaning": "mean-spirited", "lesson": 9 },
{ "kana": "おどる", "kanji": "踊る", "meaning": "to dance", "lesson": 9 },
{ "kana": "おわる", "kanji": "終わる", "meaning": "(something) ends", "lesson": 9 },
{ "kana": "にんきがある", "kanji": "人気がある", "meaning": "to be popular", "lesson": 9 },
{ "kana": "はじまる", "kanji": "始まる", "meaning": "(something) begins", "lesson": 9 },
{ "kana": "ひく", "kanji": "弾く", "meaning": "to play (a string instrument or piano)", "lesson": 9 },
{ "kana": "もらう", "kanji": "", "meaning": "to get (from somebody)", "lesson": 9 },
{ "kana": "おぼえる", "kanji": "覚える", "meaning": "to memorize", "lesson": 9 },
{ "kana": "でる", "kanji": "出る", "meaning": "(1) to appear; to attend (2) to exit", "lesson": 9 },
{ "kana": "うんどうする", "kanji": "運動する", "meaning": "to do physical exercises", "lesson": 9 },
{ "kana": "さんぽする", "kanji": "散歩する", "meaning": "to take a walk", "lesson": 9 },
{ "kana": "ぜひ", "kanji": "是非", "meaning": "by all means", "lesson": 9 },
{ "kana": "みんな", "kanji": "", "meaning": "all", "lesson": 9 },
{ "kana": "もう", "kanji": "", "meaning": "already", "lesson": 9 },
{ "kana": "ひとつ", "kanji": "一つ", "meaning": "one", "lesson": 9 },
{ "kana": "ふたつ", "kanji": "二つ", "meaning": "two", "lesson": 9 },
{ "kana": "みっつ", "kanji": "三つ", "meaning": "three", "lesson": 9 },
{ "kana": "よっつ", "kanji": "四つ", "meaning": "four", "lesson": 9 },
{ "kana": "いつつ", "kanji": "五つ", "meaning": "five", "lesson": 9 },
{ "kana": "むっつ", "kanji": "六つ", "meaning": "six", "lesson": 9 },
{ "kana": "ななつ", "kanji": "七つ", "meaning": "seven", "lesson": 9 },
{ "kana": "やっつ", "kanji": "八つ", "meaning": "eight", "lesson": 9 },
{ "kana": "ここのつ", "kanji": "九つ", "meaning": "nine", "lesson": 9 },
{ "kana": "とお", "kanji": "十", "meaning": "ten", "lesson": 9 },
{ "kana": "あき", "kanji": "秋", "meaning": "fall", "lesson": 10 },
{ "kana": "えき", "kanji": "駅", "meaning": "station", "lesson": 10 },
{ "kana": "おかねもち", "kanji": "お金持ち", "meaning": "rich person", "lesson": 10 },
{ "kana": "かお", "kanji": "顔", "meaning": "face", "lesson": 10 },
{ "kana": "きせつ", "kanji": "季節", "meaning": "season", "lesson": 10 },
{ "kana": "クレジットカード", "kanji": "", "meaning": "credit card", "lesson": 10 },
{ "kana": "ことし", "kanji": "今年", "meaning": "this year", "lesson": 10 },
{ "kana": "サッカー", "kanji": "", "meaning": "soccer", "lesson": 10 },
{ "kana": "シャツ", "kanji": "", "meaning": "shirt", "lesson": 10 },
{ "kana": "せいかつ", "kanji": "生活", "meaning": "life; living", "lesson": 10 },
{ "kana": "せかい", "kanji": "世界", "meaning": "world", "lesson": 10 },
{ "kana": "ちかてつ", "kanji": "地下鉄", "meaning": "subway", "lesson": 10 },
{ "kana": "てぶくろ", "kanji": "手袋", "meaning": "gloves", "lesson": 10 },
{ "kana": "とこや", "kanji": "床屋", "meaning": "barber's", "lesson": 10 },
{ "kana": "はる", "kanji": "春", "meaning": "spring", "lesson": 10 },
{ "kana": "パンツ", "kanji": "", "meaning": "pants", "lesson": 10 },
{ "kana": "びよういん", "kanji": "美容院", "meaning": "beauty parlor", "lesson": 10 },
{ "kana": "びん", "kanji": "便", "meaning": "flight", "lesson": 10 },
{ "kana": "ふね", "kanji": "船", "meaning": "ship; boat", "lesson": 10 },
{ "kana": "やきゅう", "kanji": "野球", "meaning": "baseball", "lesson": 10 },
{ "kana": "ゆうめいじん", "kanji": "有名人", "meaning": "celebrity", "lesson": 10 },
{ "kana": "よやく", "kanji": "予約", "meaning": "reservation", "lesson": 10 },
{ "kana": "らいがっき", "kanji": "来学期", "meaning": "next semester", "lesson": 10 },
{ "kana": "りんご", "kanji": "", "meaning": "apple", "lesson": 10 },
{ "kana": "あたたかい", "kanji": "暖かい", "meaning": "warm", "lesson": 10 },
{ "kana": "おそい", "kanji": "遅い", "meaning": "slow; late", "lesson": 10 },
{ "kana": "すずしい", "kanji": "涼しい", "meaning": "cool (weather)", "lesson": 10 },
{ "kana": "つめたい", "kanji": "冷たい", "meaning": "cold (thing/people)", "lesson": 10 },
{ "kana": "ねむい", "kanji": "眠い", "meaning": "sleepy", "lesson": 10 },
{ "kana": "かんたん", "kanji": "簡単", "meaning": "easy; simple", "lesson": 10 },
{ "kana": "かかる", "kanji": "", "meaning": "to take (amount of time / money)", "lesson": 10 },
{ "kana": "とまる", "kanji": "泊まる", "meaning": "to stay (at a hotel, etc.)", "lesson": 10 },
{ "kana": "なる", "kanji": "", "meaning": "to become", "lesson": 10 },
{ "kana": "はらう", "kanji": "払う", "meaning": "to pay", "lesson": 10 },
{ "kana": "きめる", "kanji": "決める", "meaning": "to decide", "lesson": 10 },
{ "kana": "れんしゅうする", "kanji": "練習する", "meaning": "to practice", "lesson": 10 },
{ "kana": "あるいて", "kanji": "歩いて", "meaning": "on foot", "lesson": 10 },
{ "kana": "いちばん", "kanji": "一番", "meaning": "best", "lesson": 10 },
{ "kana": "このごろ", "kanji": "", "meaning": "these days", "lesson": 10 },
{ "kana": "どうやって", "kanji": "", "meaning": "how; by what means", "lesson": 10 },
{ "kana": "どちら", "kanji": "", "meaning": "which", "lesson": 10 },
{ "kana": "どのぐらい", "kanji": "", "meaning": "how much; how long", "lesson": 10 },
{ "kana": "はやく", "kanji": "早く", "meaning": "(do something) early; fast", "lesson": 10 },
{ "kana": "おかし", "kanji": "お菓子", "meaning": "snack; sweets", "lesson": 11 },
{ "kana": "おしょうがつ", "kanji": "お正月", "meaning": "New Year's", "lesson": 11 },
{ "kana": "おとこのこ", "kanji": "男の子", "meaning": "boy", "lesson": 11 },
{ "kana": "おもちゃ", "kanji": "", "meaning": "toy", "lesson": 11 },
{ "kana": "おんなのこ", "kanji": "女の子", "meaning": "girl", "lesson": 11 },
{ "kana": "がいこく", "kanji": "外国", "meaning": "foreign country", "lesson": 11 },
{ "kana": "かしゅ", "kanji": "歌手", "meaning": "singer", "lesson": 11 },
{ "kana": "キャンプ", "kanji": "", "meaning": "camp", "lesson": 11 },
{ "kana": "こちら", "kanji": "", "meaning": "this person (polite)", "lesson": 11 },
{ "kana": "こんがっき", "kanji": "今学期", "meaning": "this semester", "lesson": 11 },
{ "kana": "しゃちょう", "kanji": "社長", "meaning": "president of a company", "lesson": 11 },
{ "kana": "じゅぎょう", "kanji": "授業", "meaning": "class", "lesson": 11 },
{ "kana": "しょうらい", "kanji": "将来", "meaning": "future", "lesson": 11 },
{ "kana": "ドライブ", "kanji": "", "meaning": "drive", "lesson": 11 },
{ "kana": "ビール", "kanji": "", "meaning": "beer", "lesson": 11 },
{ "kana": "びじゅつかん", "kanji": "美術館", "meaning": "art museum", "lesson": 11 },
{ "kana": "ホストファミリー", "kanji": "", "meaning": "host family", "lesson": 11 },
{ "kana": "みずうみ", "kanji": "湖", "meaning": "lake", "lesson": 11 },
{ "kana": "やま", "kanji": "山", "meaning": "mountain", "lesson": 11 },
{ "kana": "ゆめ", "kanji": "夢", "meaning": "dream", "lesson": 11 },
{ "kana": "ルームメート", "kanji": "", "meaning": "roommate", "lesson": 11 },
{ "kana": "うそをつく", "kanji": "", "meaning": "to tell a lie", "lesson": 11 },
{ "kana": "おなかがすく", "kanji": "", "meaning": "to become hungry", "lesson": 11 },
{ "kana": "かう", "kanji": "飼う", "meaning": "to own (a pet)", "lesson": 11 },
{ "kana": "サボる", "kanji": "", "meaning": "to cut classes", "lesson": 11 },
{ "kana": "とる", "kanji": "取る", "meaning": "to take (a class); to get (a grade)", "lesson": 11 },
{ "kana": "ならう", "kanji": "習う", "meaning": "to learn", "lesson": 11 },
{ "kana": "のぼる", "kanji": "登る", "meaning": "to climb", "lesson": 11 },
{ "kana": "はたらく", "kanji": "働く", "meaning": "to work", "lesson": 11 },
{ "kana": "つかれる", "kanji": "疲れる", "meaning": "to get tired", "lesson": 11 },
{ "kana": "やめる", "kanji": "", "meaning": "to quit", "lesson": 11 },
{ "kana": "けんかする", "kanji": "", "meaning": "to have a fight; to quarrel", "lesson": 11 },
{ "kana": "しょうかいする", "kanji": "紹介する", "meaning": "to introduce", "lesson": 11 },
{ "kana": "ダイエットする", "kanji": "", "meaning": "to go on a diet", "lesson": 11 },
{ "kana": "ちこくする", "kanji": "遅刻する", "meaning": "to be late (for an appointment)", "lesson": 11 },
{ "kana": "りゅうがくする", "kanji": "留学する", "meaning": "to study abroad", "lesson": 11 },
{ "kana": "あと", "kanji": "後", "meaning": "after (an event)", "lesson": 11 },
{ "kana": "しゅっしん", "kanji": "出身", "meaning": "coming from", "lesson": 11 },
{ "kana": "すごく", "kanji": "", "meaning": "very", "lesson": 11 },
{ "kana": "そして", "kanji": "", "meaning": "and then", "lesson": 11 },
{ "kana": "ひさしぶり", "kanji": "久しぶり", "meaning": "it has been a long time", "lesson": 11 },
{ "kana": "まあまあ", "kanji": "", "meaning": "okay; so-so", "lesson": 11 },
{ "kana": "もっと", "kanji": "", "meaning": "more", "lesson": 11 },
{ "kana": "あし", "kanji": "足", "meaning": "leg; foot", "lesson": 12 },
{ "kana": "いみ", "kanji": "意味", "meaning": "meaning", "lesson": 12 },
{ "kana": "おなか", "kanji": "", "meaning": "stomach", "lesson": 12 },
{ "kana": "かぜ", "kanji": "風", "meaning": "cold", "lesson": 12 },
{ "kana": "かのじょ", "kanji": "彼女", "meaning": "girlfriend", "lesson": 12 },
{ "kana": "かれ", "kanji": "彼", "meaning": "boyfriend", "lesson": 12 },
{ "kana": "きおん", "kanji": "気温", "meaning": "temperature (weather)", "lesson": 12 },
{ "kana": "くもり", "kanji": "曇り", "meaning": "cloudy weather", "lesson": 12 },
{ "kana": "しあい", "kanji": "試合", "meaning": "match; game", "lesson": 12 },
{ "kana": "ジュース", "kanji": "", "meaning": "juice", "lesson": 12 },
{ "kana": "せいせき", "kanji": "成績", "meaning": "grade (on a test, etc.)", "lesson": 12 },
{ "kana": "せき", "kanji": "咳", "meaning": "cough", "lesson": 12 },
{ "kana": "のど", "kanji": "", "meaning": "throat", "lesson": 12 },
{ "kana": "は", "kanji": "歯", "meaning": "tooth", "lesson": 12 },
{ "kana": "はな", "kanji": "花", "meaning": "flower", "lesson": 12 },
{ "kana": "はれ", "kanji": "晴れ", "meaning": "sunny weather", "lesson": 12 },
{ "kana": "ふく", "kanji": "服", "meaning": "clothes", "lesson": 12 },
{ "kana": "ふつかよい", "kanji": "二日酔い", "meaning": "hangover", "lesson": 12 },
{ "kana": "プレゼント", "kanji": "", "meaning": "present", "lesson": 12 },
{ "kana": "ホームシック", "kanji": "", "meaning": "homesickness", "lesson": 12 },
{ "kana": "もの", "kanji": "物", "meaning": "thing (concrete object)", "lesson": 12 },
{ "kana": "ゆき", "kanji": "雪", "meaning": "snow", "lesson": 12 },
{ "kana": "ようじ", "kanji": "用事", "meaning": "business to take care of", "lesson": 12 },
{ "kana": "あまい", "kanji": "甘い", "meaning": "sweet", "lesson": 12 },
{ "kana": "いたい", "kanji": "痛い", "meaning": "hurt; painful", "lesson": 12 },
{ "kana": "おおい", "kanji": "多い", "meaning": "there are many...", "lesson": 12 },
{ "kana": "せまい", "kanji": "狭い", "meaning": "narrow; not spacious", "lesson": 12 },
{ "kana": "つごうがわるい", "kanji": "都合が悪い", "meaning": "inconvenient; to have a scheduling conflict", "lesson": 12 },
{ "kana": "わるい", "kanji": "悪い", "meaning": "bad", "lesson": 12 },
{ "kana": "すてき", "kanji": "素敵", "meaning": "fantastic", "lesson": 12 },
{ "kana": "かぜをひく", "kanji": "風邪をひく", "meaning": "to catch a cold", "lesson": 12 },
{ "kana": "きょうみがある", "kanji": "興味がある", "meaning": "to be interested (in ...)", "lesson": 12 },
{ "kana": "なくす", "kanji": "", "meaning": "to lose", "lesson": 12 },
{ "kana": "のどがかわく", "kanji": "のどが渇く", "meaning": "to become thirsty", "lesson": 12 },
{ "kana": "ねつがある", "kanji": "熱がある", "meaning": "to have a fever", "lesson": 12 },
{ "kana": "せきがでる", "kanji": "せきが出る", "meaning": "to cough", "lesson": 12 },
{ "kana": "わかれる", "kanji": "別れる", "meaning": "to break up; to separate", "lesson": 12 },
{ "kana": "きんちょうする", "kanji": "緊張する", "meaning": "to get nervous", "lesson": 12 },
{ "kana": "しんぱいする", "kanji": "心配する", "meaning": "to worry", "lesson": 12 },
{ "kana": "いつも", "kanji": "", "meaning": "always", "lesson": 12 },
{ "kana": "おだいじに", "kanji": "お大事に", "meaning": "Get well soon.", "lesson": 12 },
{ "kana": "げんきがない", "kanji": "元気がない", "meaning": "don't look well", "lesson": 12 },
{ "kana": "たぶん", "kanji": "多分", "meaning": "probably; maybe", "lesson": 12 },
{ "kana": "できるだけ", "kanji": "", "meaning": "as much as possible", "lesson": 12 },
{ "kana": "にさんにち", "kanji": "二三日", "meaning": "for two to three days", "lesson": 12 },
{ "kana": "はじめて", "kanji": "初めて", "meaning": "for the first time", "lesson": 12 },
{ "kana": "もうすぐ", "kanji": "", "meaning": "very soon; in a few moments/days", "lesson": 12 },
{ "kana": "ウェイター", "kanji": "", "meaning": "waiter", "lesson": 13 },
{ "kana": "おじいさん", "kanji": "", "meaning": "grandfather; old man", "lesson": 13 },
{ "kana": "おとな", "kanji": "大人", "meaning": "adult", "lesson": 13 },
{ "kana": "がいこくご", "kanji": "外国語", "meaning": "foreign language", "lesson": 13 },
{ "kana": "がっき", "kanji": "楽器", "meaning": "musical instrument", "lesson": 13 },
{ "kana": "からて", "kanji": "空手", "meaning": "karate", "lesson": 13 },
{ "kana": "カレー", "kanji": "", "meaning": "curry", "lesson": 13 },
{ "kana": "きもの", "kanji": "着物", "meaning": "kimono; Japanese traditional dress", "lesson": 13 },
{ "kana": "ケーキ", "kanji": "", "meaning": "cake", "lesson": 13 },
{ "kana": "こうこく", "kanji": "広告", "meaning": "advertisement", "lesson": 13 },
{ "kana": "こうちゃ", "kanji": "紅茶", "meaning": "tea (black tea)", "lesson": 13 },
{ "kana": "ことば", "kanji": "言葉", "meaning": "language", "lesson": 13 },
{ "kana": "ゴルフ", "kanji": "", "meaning": "golf", "lesson": 13 },
{ "kana": "セーター", "kanji": "", "meaning": "sweater", "lesson": 13 },
{ "kana": "ぞう", "kanji": "象", "meaning": "elephant", "lesson": 13 },
{ "kana": "バイオリン", "kanji": "", "meaning": "violin", "lesson": 13 },
{ "kana": "バイク", "kanji": "", "meaning": "motorbike", "lesson": 13 },
{ "kana": "ぶっか", "kanji": "物価", "meaning": "(consumer) prices", "lesson": 13 },
{ "kana": "ぶんぽう", "kanji": "文法", "meaning": "grammar", "lesson": 13 },
{ "kana": "べんごし", "kanji": "弁護士", "meaning": "lawyer", "lesson": 13 },
{ "kana": "ぼしゅう", "kanji": "募集", "meaning": "recruitment", "lesson": 13 },
{ "kana": "みせ", "kanji": "店", "meaning": "shop; store", "lesson": 13 },
{ "kana": "やくざ", "kanji": "", "meaning": "yakuza; gangster", "lesson": 13 },
{ "kana": "やくそく", "kanji": "約束", "meaning": "promise; appointment", "lesson": 13 },
{ "kana": "レポート", "kanji": "", "meaning": "(term) paper", "lesson": 13 },
{ "kana": "わたくし", "kanji": "私", "meaning": "I (formal)", "lesson": 13 },
{ "kana": "うれしい", "kanji": "", "meaning": "glad", "lesson": 13 },
{ "kana": "かなしい", "kanji": "悲しい", "meaning": "sad", "lesson": 13 },
{ "kana": "からい", "kanji": "辛い", "meaning": "hot and spicy; salty", "lesson": 13 },
{ "kana": "きびしい", "kanji": "厳しい", "meaning": "strict", "lesson": 13 },
{ "kana": "ちかい", "kanji": "近い", "meaning": "close; near", "lesson": 13 },
{ "kana": "いろいろ", "kanji": "", "meaning": "various; different kinds of", "lesson": 13 },
{ "kana": "しあわせ", "kanji": "幸せ", "meaning": "happy (lasting happiness)", "lesson": 13 },
{ "kana": "だめ", "kanji": "", "meaning": "no good", "lesson": 13 },
{ "kana": "あむ", "kanji": "編む", "meaning": "to knit", "lesson": 13 },
{ "kana": "かす", "kanji": "貸す", "meaning": "to lend; to rent", "lesson": 13 },
{ "kana": "がんばる", "kanji": "頑張る", "meaning": "to do one's best; to try hard", "lesson": 13 },
{ "kana": "なく", "kanji": "泣く", "meaning": "to cry", "lesson": 13 },
{ "kana": "みがく", "kanji": "磨く", "meaning": "to brush (teeth); to polish", "lesson": 13 },
{ "kana": "やくそくをまもる", "kanji": "約束を守る", "meaning": "to keep a promise", "lesson": 13 },
{ "kana": "かんどうする", "kanji": "感動する", "meaning": "to be moved/touched (by ...)", "lesson": 13 },
{ "kana": "いらっしゃいます", "kanji": "", "meaning": "(someone honorable) is present/home", "lesson": 13 },
{ "kana": "じつは", "kanji": "実は", "meaning": "as a matter of fact, ...", "lesson": 13 },
{ "kana": "ぜんぶ", "kanji": "全部", "meaning": "all", "lesson": 13 },
{ "kana": "いちにち", "kanji": "一日", "meaning": "one day", "lesson": 13 },
{ "kana": "ふつか", "kanji": "二日", "meaning": "two days", "lesson": 13 },
{ "kana": "みっか", "kanji": "三日", "meaning": "three days", "lesson": 13 },
{ "kana": "よっか", "kanji": "四日", "meaning": "four days", "lesson": 13 },
{ "kana": "いつか", "kanji": "五日", "meaning": "five days", "lesson": 13 },
{ "kana": "むいか", "kanji": "六日", "meaning": "six days", "lesson": 13 },
{ "kana": "なのか", "kanji": "七日", "meaning": "seven days", "lesson": 13 },
{ "kana": "ようか", "kanji": "八日", "meaning": "eight days", "lesson": 13 },
{ "kana": "ここのか", "kanji": "九日", "meaning": "nine days", "lesson": 13 },
{ "kana": "とおか", "kanji": "十日", "meaning": "ten days", "lesson": 13 },
{ "kana": "よろしくおねがいします", "kanji": "よろしくお願いします", "meaning": "Thank you (in advance)", "lesson": 13 },
{ "kana": "ぬいぐるみ", "kanji": "", "meaning": "stuffed animal (e.g., teddy bear)", "lesson": 14 },
{ "kana": "あに", "kanji": "兄", "meaning": "(my) older brother", "lesson": 14 },
{ "kana": "おおやさん", "kanji": "大家さん", "meaning": "landlord", "lesson": 14 },
{ "kana": "おかえし", "kanji": "お返し", "meaning": "return (as a token of gratitude)", "lesson": 14 },
{ "kana": "おくさん", "kanji": "奥さん", "meaning": "(your/his) wife", "lesson": 14 },
{ "kana": "おじさん", "kanji": "", "meaning": "uncle; middle-aged man", "lesson": 14 },
{ "kana": "おばさん", "kanji": "", "meaning": "aunt; middle-aged woman", "lesson": 14 },
{ "kana": "クラブ", "kanji": "", "meaning": "club; student society", "lesson": 14 },
{ "kana": "クリスマス", "kanji": "", "meaning": "Christmas", "lesson": 14 },
{ "kana": "ごしゅじん", "kanji": "", "meaning": "(your/her) husband", "lesson": 14 },
{ "kana": "コップ", "kanji": "", "meaning": "tumbler; glass", "lesson": 14 },
{ "kana": "さら", "kanji": "皿", "meaning": "plate; dish", "lesson": 14 },
{ "kana": "じかん", "kanji": "時間", "meaning": "time", "lesson": 14 },
{ "kana": "チョコレート", "kanji": "", "meaning": "chocolate", "lesson": 14 },
{ "kana": "でんしメール", "kanji": "電子メール", "meaning": "e-mail", "lesson": 14 },
{ "kana": "ネクタイ", "kanji": "", "meaning": "necktie", "lesson": 14 },
{ "kana": "はは", "kanji": "母", "meaning": "(my) mother", "lesson": 14 },
{ "kana": "バレンタインデー", "kanji": "", "meaning": "St. Valentine's Day", "lesson": 14 },
{ "kana": "ビデオカメラ", "kanji": "", "meaning": "camcorder", "lesson": 14 },
{ "kana": "ふうふ", "kanji": "夫婦", "meaning": "married couple; husband and wife", "lesson": 14 },
{ "kana": "ホワイトデー", "kanji": "", "meaning": "White Day", "lesson": 14 },
{ "kana": "マフラー", "kanji": "", "meaning": "winter scarf", "lesson": 14 },
{ "kana": "まんが", "kanji": "漫画", "meaning": "comic book", "lesson": 14 },
{ "kana": "マンション", "kanji": "", "meaning": "multistory apartment; condominium", "lesson": 14 },
{ "kana": "みかん", "kanji": "", "meaning": "mandarin", "lesson": 14 },
{ "kana": "ゆびわ", "kanji": "指輪", "meaning": "ring", "lesson": 14 },
{ "kana": "りょうしん", "kanji": "両親", "meaning": "parents", "lesson": 14 },
{ "kana": "りれきしょ", "kanji": "履歴書", "meaning": "resume", "lesson": 14 },
{ "kana": "ほしい", "kanji": "欲しい", "meaning": "to want", "lesson": 14 },
{ "kana": "けち", "kanji": "", "meaning": "stingy; cheap", "lesson": 14 },
{ "kana": "おくる", "kanji": "送る", "meaning": "to send", "lesson": 14 },
{ "kana": "にあう", "kanji": "似合う", "meaning": "to look good (on somebody)", "lesson": 14 },
{ "kana": "あきらめる", "kanji": "", "meaning": "to give up", "lesson": 14 },
{ "kana": "あげる", "kanji": "", "meaning": "to give (to others)", "lesson": 14 },
{ "kana": "くれる", "kanji": "", "meaning": "to give (me)", "lesson": 14 },
{ "kana": "できる", "kanji": "", "meaning": "to come into existence; to be made", "lesson": 14 },
{ "kana": "そうだんする", "kanji": "相談する", "meaning": "to consult", "lesson": 14 },
{ "kana": "プロポーズする", "kanji": "", "meaning": "to propose marriage", "lesson": 14 },
{ "kana": "おなじ", "kanji": "同じ", "meaning": "same", "lesson": 14 },
{ "kana": "きょねん", "kanji": "去年", "meaning": "last year", "lesson": 14 },
{ "kana": "わたしたち", "kanji": "私たち", "meaning": "we", "lesson": 14 },
{ "kana": "ちょうど", "kanji": "", "meaning": "exactly", "lesson": 14 },
{ "kana": "よく", "kanji": "", "meaning": "well", "lesson": 14 },
{ "kana": "こ", "kanji": "個", "meaning": "[generic counter for smaller items]", "lesson": 14 },
{ "kana": "さつ", "kanji": "冊", "meaning": "[counter for bound volumes]", "lesson": 14 },
{ "kana": "だい", "kanji": "台", "meaning": "[counter for equipment]", "lesson": 14 },
{ "kana": "ひき", "kanji": "匹", "meaning": "[counter for smaller animals]", "lesson": 14 },
{ "kana": "ぽん", "kanji": "本", "meaning": "[counter for long objects]", "lesson": 14 },
{ "kana": "え", "kanji": "絵", "meaning": "painting; picture; drawing", "lesson": 15 },
{ "kana": "えいがかん", "kanji": "映画館", "meaning": "movie theater", "lesson": 15 },
{ "kana": "がいこくじん", "kanji": "外国人", "meaning": "foreigner", "lesson": 15 },
{ "kana": "かぐ", "kanji": "家具", "meaning": "furniture", "lesson": 15 },
{ "kana": "かんこう", "kanji": "観光", "meaning": "sightseeing", "lesson": 15 },
{ "kana": "けっこんしき", "kanji": "結婚式", "meaning": "wedding", "lesson": 15 },
{ "kana": "じしん", "kanji": "地震", "meaning": "earthquake", "lesson": 15 },
{ "kana": "しめきり", "kanji": "締め切り", "meaning": "deadline", "lesson": 15 },
{ "kana": "ジャケット", "kanji": "", "meaning": "jacket", "lesson": 15 },
{ "kana": "しゅうかん", "kanji": "習慣", "meaning": "custom", "lesson": 15 },
{ "kana": "ぜいきん", "kanji": "税金", "meaning": "tax", "lesson": 15 },
{ "kana": "そつぎょうしき", "kanji": "卒業式", "meaning": "graduation ceremony", "lesson": 15 },
{ "kana": "そば", "kanji": "", "meaning": "Japanese buckwheat noodle", "lesson": 15 },
{ "kana": "ちず", "kanji": "地図", "meaning": "map", "lesson": 15 },
{ "kana": "でんち", "kanji": "電池", "meaning": "battery", "lesson": 15 },
{ "kana": "にわ", "kanji": "庭", "meaning": "garden", "lesson": 15 },
{ "kana": "はっぴょう", "kanji": "発表", "meaning": "presentation", "lesson": 15 },
{ "kana": "ばんぐみ", "kanji": "番組", "meaning": "broadcast program", "lesson": 15 },
{ "kana": "プール", "kanji": "", "meaning": "swimming pool", "lesson": 15 },
{ "kana": "ペット", "kanji": "", "meaning": "pet", "lesson": 15 },
{ "kana": "よてい", "kanji": "予定", "meaning": "schedule", "lesson": 15 },
{ "kana": "りょかん", "kanji": "旅館", "meaning": "inn", "lesson": 15 },
{ "kana": "わりびきけん", "kanji": "割引券", "meaning": "discount coupon", "lesson": 15 },
{ "kana": "ひろい", "kanji": "広い", "meaning": "spacious; wide", "lesson": 15 },
{ "kana": "うる", "kanji": "売る", "meaning": "to sell", "lesson": 15 },
{ "kana": "おろす", "kanji": "下ろす", "meaning": "to withdraw (money)", "lesson": 15 },
{ "kana": "かく", "kanji": "", "meaning": "to draw; to paint", "lesson": 15 },
{ "kana": "さがす", "kanji": "探す", "meaning": "to look for", "lesson": 15 },
{ "kana": "さそう", "kanji": "誘う", "meaning": "to invite", "lesson": 15 },
{ "kana": "つきあう", "kanji": "付き合う", "meaning": "(1) to date (someone) (2) to keep company", "lesson": 15 },
{ "kana": "つく", "kanji": "着く", "meaning": "to arrive", "lesson": 15 },
{ "kana": "ほけんにはいる", "kanji": "保険に入る", "meaning": "to buy insurance", "lesson": 15 },
{ "kana": "きをつける", "kanji": "気をつける", "meaning": "to be cautious/careful", "lesson": 15 },
{ "kana": "しらべる", "kanji": "調べる", "meaning": "to look into (a matter)", "lesson": 15 },
{ "kana": "すてる", "kanji": "捨てる", "meaning": "to throw away", "lesson": 15 },
{ "kana": "みえる", "kanji": "見える", "meaning": "to be visible", "lesson": 15 },
{ "kana": "する", "kanji": "", "meaning": "to decide on (an item)", "lesson": 15 },
{ "kana": "そつぎょうする", "kanji": "卒業する", "meaning": "to graduate (from ...)", "lesson": 15 },
{ "kana": "よやくする", "kanji": "予約する", "meaning": "to reserve", "lesson": 15 },
{ "kana": "いちにちじゅう", "kanji": "一日中", "meaning": "all day long", "lesson": 15 },
{ "kana": "さいきん", "kanji": "最近", "meaning": "recently", "lesson": 15 },
{ "kana": "えきいん", "kanji": "駅員", "meaning": "station attendant", "lesson": 16 },
{ "kana": "おや", "kanji": "親", "meaning": "parent", "lesson": 16 },
{ "kana": "ごみ", "kanji": "", "meaning": "garbage", "lesson": 16 },
{ "kana": "さとう", "kanji": "砂糖", "meaning": "sugar", "lesson": 16 },
{ "kana": "しょうがくきん", "kanji": "奨学金", "meaning": "scholarship", "lesson": 16 },
{ "kana": "しんせき", "kanji": "親せき", "meaning": "relatives", "lesson": 16 },
{ "kana": "すいせんじょう", "kanji": "推薦状", "meaning": "letter of recommendation", "lesson": 16 },
{ "kana": "だいがくいん", "kanji": "大学院", "meaning": "graduate school", "lesson": 16 },
{ "kana": "たいふう", "kanji": "台風", "meaning": "typhoon", "lesson": 16 },
{ "kana": "ひ", "kanji": "日", "meaning": "day", "lesson": 16 },
{ "kana": "ファイル", "kanji": "", "meaning": "file; portfolio", "lesson": 16 },
{ "kana": "みち", "kanji": "道", "meaning": "way; road; directions", "lesson": 16 },
{ "kana": "めざましどけい", "kanji": "目覚まし時計", "meaning": "alarm clock", "lesson": 16 },
{ "kana": "きたない", "kanji": "汚い", "meaning": "dirty", "lesson": 16 },
{ "kana": "おこす", "kanji": "起こす", "meaning": "to wake (someone) up", "lesson": 16 },
{ "kana": "おごる", "kanji": "", "meaning": "to treat (someone) to a meal", "lesson": 16 },
{ "kana": "おちこむ", "kanji": "落ち込む", "meaning": "to get depressed", "lesson": 16 },
{ "kana": "こまる", "kanji": "困る", "meaning": "to have difficulty", "lesson": 16 },
{ "kana": "だす", "kanji": "出す", "meaning": "to take (something) out; to hand in (something)", "lesson": 16 },
{ "kana": "つれていく", "kanji": "連れていく", "meaning": "to take (someone) to (a place)", "lesson": 16 },
{ "kana": "なおす", "kanji": "直す", "meaning": "to correct; to fix", "lesson": 16 },
{ "kana": "みちにまよう", "kanji": "道に迷う", "meaning": "to become lost; to lose one's way", "lesson": 16 },
{ "kana": "やくす", "kanji": "訳す", "meaning": "to translate", "lesson": 16 },
{ "kana": "わらう", "kanji": "笑う", "meaning": "to laugh", "lesson": 16 },
{ "kana": "アイロンをかける", "kanji": "", "meaning": "to iron (clothes)", "lesson": 16 },
{ "kana": "あつめる", "kanji": "集める", "meaning": "to collect", "lesson": 16 },
{ "kana": "いれる", "kanji": "入れる", "meaning": "to put (something) in", "lesson": 16 },
{ "kana": "のりおくれる", "kanji": "乗り遅れる", "meaning": "to miss (a train, bus, etc.)", "lesson": 16 },
{ "kana": "みせる", "kanji": "見せる", "meaning": "to show", "lesson": 16 },
{ "kana": "あさねぼうする", "kanji": "朝寝坊する", "meaning": "to oversleep", "lesson": 16 },
{ "kana": "あんないする", "kanji": "案内する", "meaning": "to show (someone) around", "lesson": 16 },
{ "kana": "せつめいする", "kanji": "説明する", "meaning": "to explain", "lesson": 16 },
{ "kana": "むかえにくる", "kanji": "迎えに来る", "meaning": "to come to pick up (someone)", "lesson": 16 },
{ "kana": "ええと", "kanji": "", "meaning": "well...; let me see...", "lesson": 16 },
{ "kana": "きょうじゅうに", "kanji": "今日中に", "meaning": "by the end of today", "lesson": 16 },
{ "kana": "このあいだ", "kanji": "この間", "meaning": "the other day", "lesson": 16 },
{ "kana": "このぐらい", "kanji": "", "meaning": "about this much", "lesson": 16 },
{ "kana": "ごめん", "kanji": "", "meaning": "I'm sorry. (casual)", "lesson": 16 },
{ "kana": "しつれいします", "kanji": "失礼します", "meaning": "Excuse me..; Sorry to interrupt you.", "lesson": 16 },
{ "kana": "じぶんで", "kanji": "自分で", "meaning": "(do something) oneself", "lesson": 16 },
{ "kana": "じゅぎょうちゅうに", "kanji": "授業中に", "meaning": "in class; during the class", "lesson": 16 },
{ "kana": "ほかの", "kanji": "", "meaning": "other", "lesson": 16 },
{ "kana": "おきゃくさん", "kanji": "お客さん", "meaning": "guest; visitor; client; customer", "lesson": 17 },
{ "kana": "おとこ", "kanji": "男", "meaning": "man", "lesson": 17 },
{ "kana": "おゆ", "kanji": "お湯", "meaning": "hot water", "lesson": 17 },
{ "kana": "おんな", "kanji": "女", "meaning": "woman", "lesson": 17 },
{ "kana": "かぎ", "kanji": "", "meaning": "key", "lesson": 17 },
{ "kana": "かみ", "kanji": "紙", "meaning": "paper", "lesson": 17 },
{ "kana": "きゅうりょう", "kanji": "給料", "meaning": "salary", "lesson": 17 },
{ "kana": "コンタクト", "kanji": "", "meaning": "contact lenses", "lesson": 17 },
{ "kana": "さいてい", "kanji": "最低", "meaning": "the lowest; the worst", "lesson": 17 },
{ "kana": "サラリーマン", "kanji": "", "meaning": "salaryman; company employee", "lesson": 17 },
{ "kana": "ざんぎょう", "kanji": "残業", "meaning": "overtime work", "lesson": 17 },
{ "kana": "ストーブ", "kanji": "", "meaning": "heater", "lesson": 17 },
{ "kana": "たからくじ", "kanji": "宝くじ", "meaning": "lottery", "lesson": 17 },
{ "kana": "ちがい", "kanji": "違い", "meaning": "difference", "lesson": 17 },
{ "kana": "ニュース", "kanji": "", "meaning": "news", "lesson": 17 },
{ "kana": "ひげ", "kanji": "", "meaning": "beard", "lesson": 17 },
{ "kana": "ひみつ", "kanji": "秘密", "meaning": "secret", "lesson": 17 },
{ "kana": "りょう", "kanji": "寮", "meaning": "dormitory", "lesson": 17 },
{ "kana": "りょこうがいしゃ", "kanji": "旅行会社", "meaning": "travel agency", "lesson": 17 },
{ "kana": "うらやましい", "kanji": "", "meaning": "envious", "lesson": 17 },
{ "kana": "すくない", "kanji": "少ない", "meaning": "a little; a few", "lesson": 17 },
{ "kana": "つよい", "kanji": "強い", "meaning": "strong", "lesson": 17 },
{ "kana": "えらぶ", "kanji": "選ぶ", "meaning": "to choose; to select", "lesson": 17 },
{ "kana": "かみをとかす", "kanji": "髪をとかす", "meaning": "to comb one's hair", "lesson": 17 },
{ "kana": "おゆをわかす", "kanji": "お湯を沸かす", "meaning": "to boil water", "lesson": 17 },
{ "kana": "こむ", "kanji": "込む", "meaning": "to get crowded", "lesson": 17 },
{ "kana": "たからくじにあたる", "kanji": "宝くじに当たる", "meaning": "to win a lottery", "lesson": 17 },
{ "kana": "ぬぐ", "kanji": "脱ぐ", "meaning": "to take off (clothes)", "lesson": 17 },
{ "kana": "ひげをそる", "kanji": "", "meaning": "to shave one's beard", "lesson": 17 },
{ "kana": "いれる", "kanji": "", "meaning": "to make tea, coffee, etc.", "lesson": 17 },
{ "kana": "かぎをかける", "kanji": "", "meaning": "to lock", "lesson": 17 },
{ "kana": "たりる", "kanji": "足りる", "meaning": "to be sufficient; to be enough", "lesson": 17 },
{ "kana": "なれる", "kanji": "慣れる", "meaning": "to get used to...", "lesson": 17 },
{ "kana": "けしょうする", "kanji": "化粧する", "meaning": "to put makeup on", "lesson": 17 },
{ "kana": "しゅうしょくする", "kanji": "就職する", "meaning": "to get a full-time job (at...)", "lesson": 17 },
{ "kana": "する", "kanji": "", "meaning": "to wear small items (necktie, watch, etc.)", "lesson": 17 },
{ "kana": "りこんする", "kanji": "離婚する", "meaning": "to get a divorce", "lesson": 17 },
{ "kana": "おめでとうございます", "kanji": "", "meaning": "Congratulations!", "lesson": 17 },
{ "kana": "じぶん", "kanji": "自分", "meaning": "oneself", "lesson": 17 },
{ "kana": "ずいぶん", "kanji": "", "meaning": "very", "lesson": 17 },
{ "kana": "そうか", "kanji": "", "meaning": "I see. (casual)", "lesson": 17 },
{ "kana": "それに", "kanji": "", "meaning": "moreover, ...", "lesson": 17 },
{ "kana": "たとえば", "kanji": "例えば", "meaning": "for example", "lesson": 17 },
{ "kana": "〜にくらべて", "kanji": "〜に比べて", "meaning": "compared with ...", "lesson": 17 },
{ "kana": "〜によると", "kanji": "", "meaning": "according to ...", "lesson": 17 },
{ "kana": "まえ", "kanji": "前", "meaning": "before...", "lesson": 17 },
{ "kana": "やっぱり", "kanji": "", "meaning": "after all", "lesson": 17 },
{ "kana": "あと", "kanji": "後", "meaning": "the rest", "lesson": 18 },
{ "kana": "エアコン", "kanji": "", "meaning": "air conditioner", "lesson": 18 },
{ "kana": "カーテン", "kanji": "", "meaning": "curtain", "lesson": 18 },
{ "kana": "ぎゅうにゅう", "kanji": "牛乳", "meaning": "milk", "lesson": 18 },
{ "kana": "シャンプー", "kanji": "", "meaning": "shampoo", "lesson": 18 },
{ "kana": "スイッチ", "kanji": "", "meaning": "switch", "lesson": 18 },
{ "kana": "スカート", "kanji": "", "meaning": "skirt", "lesson": 18 },
{ "kana": "しょうゆ", "kanji": "しょう油", "meaning": "soy sauce", "lesson": 18 },
{ "kana": "そと", "kanji": "外", "meaning": "outside", "lesson": 18 },
{ "kana": "タオル", "kanji": "", "meaning": "towel", "lesson": 18 },
{ "kana": "にっき", "kanji": "日記", "meaning": "diary", "lesson": 18 },
{ "kana": "ポップコーン", "kanji": "", "meaning": "popcorn", "lesson": 18 },
{ "kana": "やちん", "kanji": "家賃", "meaning": "rent", "lesson": 18 },
{ "kana": "ゆうがた", "kanji": "夕方", "meaning": "evening", "lesson": 18 },
{ "kana": "ラジカセ", "kanji": "", "meaning": "cassette player with a radio", "lesson": 18 },
{ "kana": "るすばんでんわ", "kanji": "留守番電話", "meaning": "answering machine", "lesson": 18 },
{ "kana": "れいぞうこ", "kanji": "冷蔵庫", "meaning": "refrigerator", "lesson": 18 },
{ "kana": "ろうそく", "kanji": "", "meaning": "candle", "lesson": 18 },
{ "kana": "あかるい", "kanji": "明るい", "meaning": "bright", "lesson": 18 },
{ "kana": "きぶんがわるい", "kanji": "気分が悪い", "meaning": "to feel sick", "lesson": 18 },
{ "kana": "はずかしい", "kanji": "恥ずかしい", "meaning": "embarassing; to feel embarassed", "lesson": 18 },
{ "kana": "あく", "kanji": "開く", "meaning": "(something) opens", "lesson": 18 },
{ "kana": "あやまる", "kanji": "謝る", "meaning": "to apologize", "lesson": 18 },
{ "kana": "おす", "kanji": "押す", "meaning": "to press; to push", "lesson": 18 },
{ "kana": "おとす", "kanji": "落とす", "meaning": "to drop (something)", "lesson": 18 },
{ "kana": "おゆがわく", "kanji": "お湯が沸く", "meaning": "water boils", "lesson": 18 },
{ "kana": "ころぶ", "kanji": "転ぶ", "meaning": "to fall down", "lesson": 18 },
{ "kana": "こわす", "kanji": "壊す", "meaning": "to break (something)", "lesson": 18 },
{ "kana": "さく", "kanji": "咲く", "meaning": "to bloom", "lesson": 18 },
{ "kana": "しまる", "kanji": "閉まる", "meaning": "(something) closes", "lesson": 18 },
{ "kana": "たすかる", "kanji": "助かる", "meaning": "to be saved; to be helped", "lesson": 18 },
{ "kana": "たのむ", "kanji": "頼む", "meaning": "to ask (a favor)", "lesson": 18 },
{ "kana": "つく", "kanji": "", "meaning": "(something) turns on", "lesson": 18 },
{ "kana": "よごす", "kanji": "汚す", "meaning": "to make dirty", "lesson": 18 },
{ "kana": "おちる", "kanji": "落ちる", "meaning": "(something) drops", "lesson": 18 },
{ "kana": "かんがえる", "kanji": "考える", "meaning": "to think (about); to consider", "lesson": 18 },
{ "kana": "きえる", "kanji": "消える", "meaning": "(something) goes off", "lesson": 18 },
{ "kana": "こわれる", "kanji": "壊れる", "meaning": "(something) breaks", "lesson": 18 },
{ "kana": "よごれる", "kanji": "汚れる", "meaning": "to become dirty", "lesson": 18 },
{ "kana": "ちゅうもんする", "kanji": "注文する", "meaning": "to place an order", "lesson": 18 },
{ "kana": "いますぐ", "kanji": "今すぐ", "meaning": "right away", "lesson": 18 },
{ "kana": "おかげで", "kanji": "", "meaning": "thanks to ...", "lesson": 18 },
{ "kana": "おさきにしつれいします", "kanji": "お先に失礼します", "meaning": "See you. (lit., I'm leaving ahead of you.)", "lesson": 18 },
{ "kana": "おつかれさまでした", "kanji": "お疲れ様でした", "meaning": "You must be tired after working so hard. (ritualistic expression)", "lesson": 18 },
{ "kana": "ほんとうに", "kanji": "本当に", "meaning": "really", "lesson": 18 },
{ "kana": "まず", "kanji": "", "meaning": "first of all", "lesson": 18 },
{ "kana": "〜までに", "kanji": "", "meaning": "by (time/date)", "lesson": 18 },
{ "kana": "どうしよう", "kanji": "", "meaning": "What should I/we do?", "lesson": 18 },
{ "kana": "しょうたいする", "kanji": "招待する", "meaning": "to invite someone (to an event/a place)", "lesson": 19 },
{ "kana": "おくさま", "kanji": "奥様", "meaning": "(your/his) wife (polite)", "lesson": 19 },
{ "kana": "おこさん", "kanji": "お子さん", "meaning": "(your/their) child (polite)", "lesson": 19 },
{ "kana": "おれい", "kanji": "お礼", "meaning": "expression of gratitude", "lesson": 19 },
{ "kana": "けいご", "kanji": "敬語", "meaning": "honorific language", "lesson": 19 },
{ "kana": "こちら", "kanji": "", "meaning": "this way (polite)", "lesson": 19 },
{ "kana": "しゅっちょう", "kanji": "出張", "meaning": "business trip", "lesson": 19 },
{ "kana": "しゅるい", "kanji": "種類", "meaning": "a kind; a sort", "lesson": 19 },
{ "kana": "せいかく", "kanji": "性格", "meaning": "personality", "lesson": 19 },
{ "kana": "ちゅうがくせい", "kanji": "中学生", "meaning": "junior high school student", "lesson": 19 },
{ "kana": "どちら", "kanji": "", "meaning": "where (polite)", "lesson": 19 },
{ "kana": "なまけもの", "kanji": "怠け者", "meaning": "lazy person", "lesson": 19 },
{ "kana": "なやみ", "kanji": "悩み", "meaning": "worry", "lesson": 19 },
{ "kana": "はずかしがりや", "kanji": "恥ずかしがり屋", "meaning": "shy person", "lesson": 19 },
{ "kana": "はなし", "kanji": "話", "meaning": "chat; talk", "lesson": 19 },
{ "kana": "ぶちょう", "kanji": "部長", "meaning": "department manager", "lesson": 19 },
{ "kana": "ぶんか", "kanji": "文化", "meaning": "culture", "lesson": 19 },
{ "kana": "まちがい", "kanji": "間違い", "meaning": "mistake", "lesson": 19 },
{ "kana": "なかがいい", "kanji": "仲がいい", "meaning": "be on good/close terms; to get along well", "lesson": 19 },
{ "kana": "まじめ", "kanji": "", "meaning": "serious; sober; diligent", "lesson": 19 },
{ "kana": "いらっしゃる", "kanji": "", "meaning": "honorific expression for いく, くる, and いる", "lesson": 19 },
{ "kana": "おくる", "kanji": "送る", "meaning": "to walk/drive (someone)", "lesson": 19 },
{ "kana": "おこる", "kanji": "怒る", "meaning": "to get angry", "lesson": 19 },
{ "kana": "おっしゃる", "kanji": "", "meaning": "honorific expression for いう", "lesson": 19 },
{ "kana": "おやすみになる", "kanji": "お休みになる", "meaning": "honorific expression for ねる", "lesson": 19 },
{ "kana": "きまる", "kanji": "決まる", "meaning": "to be decided", "lesson": 19 },
{ "kana": "くださる", "kanji": "下さる", "meaning": "honorific expression for くれる", "lesson": 19 },
{ "kana": "ごらんになる", "kanji": "ご覧になる", "meaning": "honorific expression for みる", "lesson": 19 },
{ "kana": "しりあう", "kanji": "知り合う", "meaning": "to get aquainted with", "lesson": 19 },
{ "kana": "〜ていらっしゃる", "kanji": "", "meaning": "honorific expression for 〜ている", "lesson": 19 },
{ "kana": "なさる", "kanji": "", "meaning": "honorific expression for する", "lesson": 19 },
{ "kana": "ひっこす", "kanji": "引っ越す", "meaning": "to move (to another place to live)", "lesson": 19 },
{ "kana": "めしあがる", "kanji": "召し上がる", "meaning": "honorific expression for たべる and のむ", "lesson": 19 },
{ "kana": "よぶ", "kanji": "呼ぶ", "meaning": "to call (one's name); to invite", "lesson": 19 },
{ "kana": "よる", "kanji": "寄る", "meaning": "to stop by", "lesson": 19 },
{ "kana": "おくれる", "kanji": "遅れる", "meaning": "to become late", "lesson": 19 },
{ "kana": "かける", "kanji": "", "meaning": "to sit down", "lesson": 19 },
{ "kana": "はれる", "kanji": "晴れる", "meaning": "to become sunny", "lesson": 19 },
{ "kana": "もてる", "kanji": "", "meaning": "to be popular (in terms of romantic interest)", "lesson": 19 },
{ "kana": "えんりょする", "kanji": "遠慮する", "meaning": "to hold back for the time being; to refrain from", "lesson": 19 },
{ "kana": "ごちそうする", "kanji": "", "meaning": "to treat/invite (someone) to a meal", "lesson": 19 },
{ "kana": "ちゅういする", "kanji": "注意する", "meaning": "to watch out; to give warning", "lesson": 19 },
{ "kana": "はなしをする", "kanji": "話をする", "meaning": "to have a talk", "lesson": 19 },
{ "kana": "おととい", "kanji": "", "meaning": "the day before yesterday", "lesson": 19 },
{ "kana": "なぜ", "kanji": "", "meaning": "why (=どうして)", "lesson": 19 },
{ "kana": "ほんとうは", "kanji": "本当は", "meaning": "in fact; originally", "lesson": 19 },
{ "kana": "まいあさ", "kanji": "毎朝", "meaning": "every morning", "lesson": 19 },
{ "kana": "まだ", "kanji": "", "meaning": "still", "lesson": 19 },
{ "kana": "〜めいさま", "kanji": "〜名様", "meaning": "party of ... people", "lesson": 19 },
{ "kana": "ようこそ", "kanji": "", "meaning": "Welcome.", "lesson": 19 },
{ "kana": "よろしくおつたえください", "kanji": "よろしくお伝えください", "meaning": "Please give my best regards (to ...)", "lesson": 19 },
{ "kana": "あちら", "kanji": "", "meaning": "this way (polite)", "lesson": 20 },
{ "kana": "うちゅうじん", "kanji": "宇宙人", "meaning": "space alien", "lesson": 20 },
{ "kana": "おと", "kanji": "音", "meaning": "sound", "lesson": 20 },
{ "kana": "かかりのもの", "kanji": "係の者", "meaning": "our person in charge", "lesson": 20 },
{ "kana": "かど", "kanji": "角", "meaning": "corner", "lesson": 20 },
{ "kana": "かみさま", "kanji": "神様", "meaning": "God", "lesson": 20 },
{ "kana": "くうこう", "kanji": "空港", "meaning": "airport", "lesson": 20 },
{ "kana": "じ", "kanji": "字", "meaning": "letter; character", "lesson": 20 },
{ "kana": "してん", "kanji": "支店", "meaning": "branch office", "lesson": 20 },
{ "kana": "しゅみ", "kanji": "趣味", "meaning": "hobby; pastime", "lesson": 20 },
{ "kana": "しょうせつ", "kanji": "小説", "meaning": "novel", "lesson": 20 },
{ "kana": "しんごう", "kanji": "信号", "meaning": "traffic light", "lesson": 20 },
{ "kana": "スニーカー", "kanji": "", "meaning": "sneakers", "lesson": 20 },
{ "kana": "せんす", "kanji": "扇子", "meaning": "fan", "lesson": 20 },
{ "kana": "つき", "kanji": "月", "meaning": "moon", "lesson": 20 },
{ "kana": "ハイヒール", "kanji": "", "meaning": "high heels", "lesson": 20 },
{ "kana": "ゆうべ", "kanji": "", "meaning": "last night", "lesson": 20 },
{ "kana": "おもい", "kanji": "重い", "meaning": "heavy; serious (illness)", "lesson": 20 },
{ "kana": "あるく", "kanji": "歩く", "meaning": "to walk", "lesson": 20 },
{ "kana": "いたす", "kanji": "致す", "meaning": "extra-modest expression for する", "lesson": 20 },
{ "kana": "いただく", "kanji": "頂く", "meaning": "extra-modest expression for たべる and のむ", "lesson": 20 },
{ "kana": "いただく", "kanji": "頂く", "meaning": "humble expression for もらう", "lesson": 20 },
{ "kana": "うかがう", "kanji": "伺う", "meaning": "to humbly visit; to humbly ask", "lesson": 20 },
{ "kana": "おる", "kanji": "", "meaning": "extra-modest expression for いる", "lesson": 20 },
{ "kana": "ござる", "kanji": "", "meaning": "extra-modest expression for ある", "lesson": 20 },
{ "kana": "〜ておる", "kanji": "", "meaning": "extra-modest expression for 〜ている", "lesson": 20 },
{ "kana": "〜でござる", "kanji": "", "meaning": "extra-modest expression for です", "lesson": 20 },
{ "kana": "まいる", "kanji": "参る", "meaning": "extra-modest expression for いく and くる", "lesson": 20 },
{ "kana": "まがる", "kanji": "曲がる", "meaning": "to turn (right/left)", "lesson": 20 },
{ "kana": "もうす", "kanji": "申す", "meaning": "extra-modest expression for いう", "lesson": 20 },
{ "kana": "もどる", "kanji": "戻る", "meaning": "to return; to come back", "lesson": 20 },
{ "kana": "きこえる", "kanji": "聞こえる", "meaning": "to be audible", "lesson": 20 },
{ "kana": "さしあげる", "kanji": "差し上げる", "meaning": "humble expression for あげる", "lesson": 20 },
{ "kana": "つたえる", "kanji": "伝える", "meaning": "to convey (message)", "lesson": 20 },
{ "kana": "またせる", "kanji": "待たせる", "meaning": "to keep (someone) waiting", "lesson": 20 },
{ "kana": "こうかんする", "kanji": "交換する", "meaning": "to exchange", "lesson": 20 },
{ "kana": "せいかつする", "kanji": "生活する", "meaning": "to lead a life", "lesson": 20 },
{ "kana": "へんぴんする", "kanji": "返品する", "meaning": "to return (merchandise)", "lesson": 20 },
{ "kana": "おや", "kanji": "", "meaning": "Oh!", "lesson": 20 },
{ "kana": "〜かい", "kanji": "〜階", "meaning": "...th floor", "lesson": 20 },
{ "kana": "かしこまりました", "kanji": "", "meaning": "Certainly.", "lesson": 20 },
{ "kana": "さあ", "kanji": "", "meaning": "I am not sure, ...", "lesson": 20 },
{ "kana": "しつれいしました", "kanji": "失礼しました", "meaning": "I'm very sorry", "lesson": 20 },
{ "kana": "しょうしょう", "kanji": "少々", "meaning": "a few seconds", "lesson": 20 },
{ "kana": "それでは", "kanji": "", "meaning": "if that is the case, ...", "lesson": 20 },
{ "kana": "できれば", "kanji": "", "meaning": "if possible", "lesson": 20 },
{ "kana": "まことに", "kanji": "誠に", "meaning": "really (very polite)", "lesson": 20 },
{ "kana": "また", "kanji": "", "meaning": "again", "lesson": 20 },
{ "kana": "もうしわけありません", "kanji": "申し訳ありません", "meaning": "You have my apologies.", "lesson": 20 },
{ "kana": "よろしかったら", "kanji": "", "meaning": "if it is okay (polite)", "lesson": 20 },
{ "kana": "あかちゃん", "kanji": "赤ちゃん", "meaning": "baby", "lesson": 21 },
{ "kana": "か", "kanji": "蚊", "meaning": "mosquito", "lesson": 21 },
{ "kana": "かいぎ", "kanji": "会議", "meaning": "business meeting; conference", "lesson": 21 },
{ "kana": "ガソリン", "kanji": "", "meaning": "gasoline", "lesson": 21 },
{ "kana": "かんきょう", "kanji": "環境", "meaning": "environment", "lesson": 21 },
{ "kana": "けいさつ", "kanji": "警察", "meaning": "police; police station", "lesson": 21 },
{ "kana": "こうじょう", "kanji": "工場", "meaning": "factory", "lesson": 21 },
{ "kana": "こと", "kanji": "事", "meaning": "things; matters", "lesson": 21 },
{ "kana": "しゅうでん", "kanji": "終電", "meaning": "last train", "lesson": 21 },
{ "kana": "スピーチ", "kanji": "", "meaning": "speech", "lesson": 21 },
{ "kana": "せいふ", "kanji": "政府", "meaning": "government", "lesson": 21 },
{ "kana": "ちかん", "kanji": "", "meaning": "sexual offender; lascivious man", "lesson": 21 },
{ "kana": "どろぼう", "kanji": "泥棒", "meaning": "burgular", "lesson": 21 },
{ "kana": "バイト", "kanji": "", "meaning": "abbreviation of アルバイト", "lesson": 21 },
{ "kana": "はんにん", "kanji": "犯人", "meaning": "criminal", "lesson": 21 },
{ "kana": "ポスター", "kanji": "", "meaning": "poster", "lesson": 21 },
{ "kana": "むかし", "kanji": "昔", "meaning": "old days; past", "lesson": 21 },
{ "kana": "もんく", "kanji": "文句", "meaning": "complaint", "lesson": 21 },
{ "kana": "もんくをいう", "kanji": "文句を言う", "meaning": "to complain", "lesson": 21 },
{ "kana": "るす", "kanji": "留守", "meaning": "absence; not at home", "lesson": 21 },
{ "kana": "とおい", "kanji": "遠い", "meaning": "far (away)", "lesson": 21 },
{ "kana": "ひどい", "kanji": "", "meaning": "awful", "lesson": 21 },
{ "kana": "あんぜん", "kanji": "安全", "meaning": "safe", "lesson": 21 },
{ "kana": "たいせつ", "kanji": "大切", "meaning": "precious; valuable", "lesson": 21 },
{ "kana": "めちゃくちゃ", "kanji": "", "meaning": "messy; disorganized", "lesson": 21 },
{ "kana": "おく", "kanji": "置く", "meaning": "to put; to lay; to place", "lesson": 21 },
{ "kana": "きがつく", "kanji": "気が付く", "meaning": "to notice", "lesson": 21 },
{ "kana": "ける", "kanji": "", "meaning": "to kick", "lesson": 21 },
{ "kana": "さす", "kanji": "刺す", "meaning": "to sting; to bite (bug); to stab", "lesson": 21 },
{ "kana": "さわる", "kanji": "触る", "meaning": "to touch", "lesson": 21 },
{ "kana": "つかまる", "kanji": "捕まる", "meaning": "to be arrested; to be caught", "lesson": 21 },
{ "kana": "つつむ", "kanji": "包む", "meaning": "to wrap; to cover", "lesson": 21 },
{ "kana": "なぐる", "kanji": "殴る", "meaning": "to strike; to hit; to punch", "lesson": 21 },
{ "kana": "ぬすむ", "kanji": "盗む", "meaning": "to steal; to rob", "lesson": 21 },
{ "kana": "はる", "kanji": "貼る", "meaning": "to post", "lesson": 21 },
{ "kana": "ふむ", "kanji": "踏む", "meaning": "to step on", "lesson": 21 },
{ "kana": "ふる", "kanji": "", "meaning": "to turn down (somebody); to reject; to jilt", "lesson": 21 },
{ "kana": "やく", "kanji": "焼く", "meaning": "to bake", "lesson": 21 },
{ "kana": "やる", "kanji": "", "meaning": "to give (to pets, plants, younger siblings, etc.)", "lesson": 21 },
{ "kana": "いじめる", "kanji": "", "meaning": "to bully", "lesson": 21 },
{ "kana": "きがえる", "kanji": "着替える", "meaning": "to change clothes", "lesson": 21 },
{ "kana": "ためる", "kanji": "", "meaning": "to save money", "lesson": 21 },
{ "kana": "つづける", "kanji": "", "meaning": "to continue", "lesson": 21 },
{ "kana": "ほめる", "kanji": "", "meaning": "to praise; to say nice things", "lesson": 21 },
{ "kana": "まちがえる", "kanji": "間違える", "meaning": "to make a mistake", "lesson": 21 },
{ "kana": "みつける", "kanji": "見つける", "meaning": "to find", "lesson": 21 },
{ "kana": "じゅんびする", "kanji": "準備する", "meaning": "to prepare", "lesson": 21 },
{ "kana": "ばかにする", "kanji": "", "meaning": "to insult; to make a fool of ...", "lesson": 21 },
{ "kana": "びっくりする", "kanji": "", "meaning": "to be surprised", "lesson": 21 },
{ "kana": "ひるねをする", "kanji": "昼寝をする", "meaning": "to take a nap", "lesson": 21 },
{ "kana": "れんらくする", "kanji": "連絡する", "meaning": "to contact", "lesson": 21 },
{ "kana": "〜あいだに", "kanji": "〜間に", "meaning": "while...", "lesson": 21 },
{ "kana": "ころ", "kanji": "", "meaning": "time of...; when...", "lesson": 21 },
{ "kana": "すこし", "kanji": "少し", "meaning": "a little", "lesson": 21 },
{ "kana": "とにかく", "kanji": "", "meaning": "anyhow; anyway", "lesson": 21 },
{ "kana": "どうりょう", "kanji": "同僚", "meaning": "colleague", "lesson": 21 },
{ "kana": "あいて", "kanji": "相手", "meaning": "partner", "lesson": 22 },
{ "kana": "うけつけ", "kanji": "受付", "meaning": "reception desk", "lesson": 22 },
{ "kana": "えいかいわ", "kanji": "英会話", "meaning": "English conversation", "lesson": 22 },
{ "kana": "おじょうさん", "kanji": "お嬢さん", "meaning": "(someone's) daughter (polite)", "lesson": 22 },
{ "kana": "かじ", "kanji": "家事", "meaning": "household matters", "lesson": 22 },
{ "kana": "かぜ", "kanji": "風", "meaning": "wind", "lesson": 22 },
{ "kana": "き", "kanji": "木", "meaning": "tree", "lesson": 22 },
{ "kana": "きまつしけん", "kanji": "期末試験", "meaning": "final examination", "lesson": 22 },
{ "kana": "こうはい", "kanji": "後輩", "meaning": "junior members of a group", "lesson": 22 },
{ "kana": "さる", "kanji": "猿", "meaning": "monkey", "lesson": 22 },
{ "kana": "じゆう", "kanji": "自由", "meaning": "freedom", "lesson": 22 },
{ "kana": "じゅく", "kanji": "塾", "meaning": "cram school", "lesson": 22 },
{ "kana": "しょるい", "kanji": "書類", "meaning": "document", "lesson": 22 },
{ "kana": "せんぱい", "kanji": "先輩", "meaning": "senior members of a group", "lesson": 22 },
{ "kana": "ひとりぐらし", "kanji": "一人暮らし", "meaning": "living alone", "lesson": 22 },
{ "kana": "ぶか", "kanji": "部下", "meaning": "subordinate", "lesson": 22 },
{ "kana": "ふくしゅう", "kanji": "復習", "meaning": "review of lessons", "lesson": 22 },
{ "kana": "プロジェクト", "kanji": "", "meaning": "project", "lesson": 22 },
{ "kana": "ボール", "kanji": "", "meaning": "ball", "lesson": 22 },
{ "kana": "むだづかい", "kanji": "無駄遣い", "meaning": "waste (money)", "lesson": 22 },
{ "kana": "めんきょ", "kanji": "免許", "meaning": "license", "lesson": 22 },
{ "kana": "よしゅう", "kanji": "予習", "meaning": "preparation of lessons", "lesson": 22 },
{ "kana": "うるさい", "kanji": "", "meaning": "noisy; annoying", "lesson": 22 },
{ "kana": "しんぱい", "kanji": "心配", "meaning": "worried about", "lesson": 22 },
{ "kana": "びんぼう", "kanji": "貧乏", "meaning": "poor", "lesson": 22 },
{ "kana": "ペラペラ", "kanji": "", "meaning": "fluent", "lesson": 22 },
{ "kana": "へん", "kanji": "変", "meaning": "strange; unusual", "lesson": 22 },
{ "kana": "らく", "kanji": "楽", "meaning": "easy; comfortable", "lesson": 22 },
{ "kana": "かつ", "kanji": "勝つ", "meaning": "to win", "lesson": 22 },
{ "kana": "コピーをとる", "kanji": "コピーを取る", "meaning": "to make a photocopy", "lesson": 22 },
{ "kana": "はこぶ", "kanji": "運ぶ", "meaning": "to carry from one place to another; transport", "lesson": 22 },
{ "kana": "はしる", "kanji": "走る", "meaning": "to run", "lesson": 22 },
{ "kana": "ひろう", "kanji": "拾う", "meaning": "to pick up (something)", "lesson": 22 },
{ "kana": "ふく", "kanji": "吹く", "meaning": "to blow", "lesson": 22 },
{ "kana": "ほうっておく", "kanji": "放っておく", "meaning": "to leave (someone/something) alone; to neglect", "lesson": 22 },
{ "kana": "まにあう", "kanji": "間に合う", "meaning": "to be in time for", "lesson": 22 },
{ "kana": "むかえにいく", "kanji": "迎えに行く", "meaning": "to go to pick up (someone)", "lesson": 22 },
{ "kana": "けいかくをたてる", "kanji": "計画を立てる", "meaning": "to make a plan", "lesson": 22 },
{ "kana": "そだてる", "kanji": "育てる", "meaning": "to raise; to bring up", "lesson": 22 },
{ "kana": "たすける", "kanji": "助ける", "meaning": "to help; to rescue", "lesson": 22 },
{ "kana": "まける", "kanji": "負ける", "meaning": "to lose (a match)", "lesson": 22 },
{ "kana": "おねがいする", "kanji": "お願いする", "meaning": "to pray for help", "lesson": 22 },
{ "kana": "さんせいする", "kanji": "賛成する", "meaning": "to agree", "lesson": 22 },
{ "kana": "しっぱいする", "kanji": "失敗する", "meaning": "to fail; to be unsuccessful", "lesson": 22 },
{ "kana": "てつやする", "kanji": "徹夜する", "meaning": "to stay up all night", "lesson": 22 },
{ "kana": "はんたいする", "kanji": "反対する", "meaning": "to oppose; to object to", "lesson": 22 },
{ "kana": "ほんやくする", "kanji": "翻訳する", "meaning": "to translate", "lesson": 22 },
{ "kana": "こんなふう", "kanji": "", "meaning": "in this way", "lesson": 22 },
{ "kana": "ずっと", "kanji": "", "meaning": "for a long time; all the time", "lesson": 22 },
{ "kana": "ぜったいに", "kanji": "絶対に", "meaning": "definitely", "lesson": 22 },
{ "kana": "そんなことはない", "kanji": "", "meaning": "I don't think so.", "lesson": 22 },
{ "kana": "〜とか", "kanji": "", "meaning": "...for example", "lesson": 22 },
{ "kana": "なんども", "kanji": "何度も", "meaning": "many times", "lesson": 22 },
{ "kana": "のんびり", "kanji": "", "meaning": "in a leisurely way", "lesson": 22 },
{ "kana": "もうすこし", "kanji": "もう少し", "meaning": "a little more", "lesson": 22 },
{ "kana": "おもいで", "kanji": "思い出", "meaning": "memory", "lesson": 23 },
{ "kana": "かいがいりょこう", "kanji": "海外旅行", "meaning": "trip to a foreign country", "lesson": 23 },
{ "kana": "からだ", "kanji": "体", "meaning": "body", "lesson": 23 },
{ "kana": "くつした", "kanji": "靴下", "meaning": "socks", "lesson": 23 },
{ "kana": "こくさいでんわ", "kanji": "国際電話", "meaning": "international call", "lesson": 23 },
{ "kana": "じゅぎょうりょう", "kanji": "授業料", "meaning": "tuition", "lesson": 23 },
{ "kana": "しょうがっこう", "kanji": "小学校", "meaning": "elementary school", "lesson": 23 },
{ "kana": "せんきょ", "kanji": "選挙", "meaning": "election", "lesson": 23 },
{ "kana": "タイヤ", "kanji": "", "meaning": "tire", "lesson": 23 },
{ "kana": "ただ", "kanji": "", "meaning": "free of charge", "lesson": 23 },
{ "kana": "ばしょ", "kanji": "場所", "meaning": "place", "lesson": 23 },
{ "kana": "べっそう", "kanji": "別荘", "meaning": "villa; vacation home", "lesson": 23 },
{ "kana": "ボーナス", "kanji": "", "meaning": "bonus", "lesson": 23 },
{ "kana": "ぼんおどり", "kanji": "盆踊り", "meaning": "Bon dance (Japanese traditional dance)", "lesson": 23 },
{ "kana": "めんせつ", "kanji": "面接", "meaning": "interview", "lesson": 23 },
{ "kana": "ゆうしょく", "kanji": "夕食", "meaning": "dinner", "lesson": 23 },
{ "kana": "りそう", "kanji": "理想", "meaning": "ideal", "lesson": 23 },
{ "kana": "るすばん", "kanji": "留守番", "meaning": "looking after a house during one's absence", "lesson": 23 },
{ "kana": "まずい", "kanji": "", "meaning": "(food is) terrible", "lesson": 23 },
{ "kana": "あめがやむ", "kanji": "雨がやむ", "meaning": "the rain stops", "lesson": 23 },
{ "kana": "いなくなる", "kanji": "", "meaning": "(someone) is gone; to disappear", "lesson": 23 },
{ "kana": "おせわになる", "kanji": "お世話になる", "meaning": "to be in someone's care", "lesson": 23 },
{ "kana": "おなかをこわす", "kanji": "", "meaning": "to have a stomachache", "lesson": 23 },
{ "kana": "ちがう", "kanji": "違う", "meaning": "to be different; wrong", "lesson": 23 },
{ "kana": "なくなる", "kanji": "", "meaning": "to be lost; to disappear", "lesson": 23 },
{ "kana": "わるぐちをいう", "kanji": "悪口を言う", "meaning": "to talk behind someone's back", "lesson": 23 },
{ "kana": "うける", "kanji": "受ける", "meaning": "to take (an examination, interview, etc.)", "lesson": 23 },
{ "kana": "かえる", "kanji": "換える", "meaning": "to change", "lesson": 23 },
{ "kana": "はなれる", "kanji": "離れる", "meaning": "(something/someone) separates; parts from", "lesson": 23 },
{ "kana": "〜かおをする", "kanji": "〜顔をする", "meaning": "to look ...(facial expression)", "lesson": 23 },
{ "kana": "がっかりする", "kanji": "", "meaning": "to be disappointed", "lesson": 23 },
{ "kana": "がまんする", "kanji": "我慢する", "meaning": "to be tolerant/patient", "lesson": 23 },
{ "kana": "せわをする", "kanji": "世話をする", "meaning": "to take care of ...", "lesson": 23 },
{ "kana": "どうじょうする", "kanji": "同情する", "meaning": "to sympathize", "lesson": 23 },
{ "kana": "パンクする", "kanji": "", "meaning": "(tire) goes flat", "lesson": 23 },
{ "kana": "もどってくる", "kanji": "戻ってくる", "meaning": "(something/someone) comes back", "lesson": 23 },
{ "kana": "ゆうしょうする", "kanji": "優勝する", "meaning": "to win a championship", "lesson": 23 },
{ "kana": "いや", "kanji": "", "meaning": "no", "lesson": 23 },
{ "kana": "げんきでね", "kanji": "元気でね", "meaning": "Take care of yourself.", "lesson": 23 },
{ "kana": "そうそう", "kanji": "", "meaning": "You are right.", "lesson": 23 },
{ "kana": "そろそろ", "kanji": "", "meaning": "it is about time to ...", "lesson": 23 },
{ "kana": "そんな〜", "kanji": "", "meaning": "such ...; that kind of ...", "lesson": 23 },
{ "kana": "ものすごく", "kanji": "", "meaning": "extremely", "lesson": 23 }];